import assert from 'node:assert/strict';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { createApp } from '../src/server.js';
import { Store } from '../src/store.js';

async function fixture({now}={}){const dir=await mkdtemp(path.join(tmpdir(),'viq-browser-code-')),db=path.join(dir,'db.sqlite'),store=new Store(db,{now});await store.init();const coordinator=await store.bootstrapCoordinator({id:'coord',name:'Coordinator'});const app=await createApp({storage:db,now});await new Promise(r=>app.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${app.address().port}`,issue=options=>store.createPairingCode('coord',options),redeem=async code=>{const response=await fetch(base+'/v1/browsers/pair',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code})});return{status:response.status,body:await response.json()}};return{app,store,coordinator,issue,redeem}}

test('Browser code-only redemption uses exact server-bound identity and remains one-use',async t=>{const f=await fixture();t.after(async()=>{f.app.close();await f.store.close()});const issued=await f.issue({intended_kind:'coordinator',actor_id:'coord',device_id:'browser-server-bound',device_name:'Server Browser'}),paired=await f.redeem(issued.code);assert.equal(paired.status,201);assert.deepEqual({id:paired.body.device.id,name:paired.body.device.name,kind:paired.body.device.kind,actor:paired.body.device.actor_id},{id:'browser-server-bound',name:'Server Browser',kind:'coordinator',actor:'coord'});assert.equal(typeof paired.body.credential,'string');assert.equal((await f.redeem(issued.code)).body.error.code,'pairing_code_used_or_invalid')});

test('Browser redemption rejects expiry, Worker kind, unbound legacy intent, and extra identity fields',async t=>{let clock=1000;const f=await fixture({now:()=>clock});t.after(async()=>{f.app.close();await f.store.close()});const expired=await f.issue({intended_kind:'coordinator',actor_id:'coord',device_id:'expired-browser',device_name:'Expired',ttl_ms:1000});clock=2000;assert.equal((await f.redeem(expired.code)).body.error.code,'pairing_code_expired');const worker=await f.issue({intended_kind:'worker',device_id:'worker-bound',device_name:'Worker'});assert.equal((await f.redeem(worker.code)).body.error.code,'pairing_kind_mismatch');const legacy=await f.issue({intended_kind:'coordinator'});assert.equal((await f.redeem(legacy.code)).body.error.code,'pairing_device_binding_required');const bound=await f.issue({intended_kind:'coordinator',actor_id:'coord',device_id:'exact-browser',device_name:'Exact'});const response=await fetch(`http://127.0.0.1:${f.app.address().port}/v1/browsers/pair`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code:bound.code,id:'invented'})});assert.equal(response.status,400);assert.equal((await response.json()).error.code,'invalid_browser_pairing_request');assert.equal((await f.redeem(bound.code)).status,201)});
