import assert from 'node:assert/strict';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import http from 'node:http';
import { DatabaseSync } from 'node:sqlite';
import test from 'node:test';
import { Store } from '../src/store.js';
import { createOperatorServer } from '../src/operator-server.js';
import { createApp } from '../src/server.js';
import { runOperatorCommand } from '../src/operator-cli.js';

const close=s=>new Promise(r=>s.close(r));
const listen=s=>new Promise(r=>s.listen(0,'127.0.0.1',r));
const post=(socketPath,payload)=>new Promise((resolve,reject)=>{const raw=JSON.stringify(payload),req=http.request({socketPath,path:'/v1/operator/projects-tickets/clean-slate',method:'POST',headers:{'content-type':'application/json','content-length':Buffer.byteLength(raw)}},res=>{let body='';res.on('data',c=>body+=c);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(body)}))});req.on('error',reject);req.end(raw)});
const counts=db=>Object.fromEntries(['projects','tickets','claims','questions','ticket_blocks','ticket_tombstones','submission_authority','ticket_projects'].map(table=>[table,Number(db.prepare(`SELECT count(*) n FROM ${table}`).get().n)]));
const identity=db=>Object.fromEntries(['actors','devices','roles','device_roles','actor_roles','pairing_codes','worker_sessions'].map(table=>[table,db.prepare(`SELECT * FROM ${table} ORDER BY rowid`).all().map(row=>JSON.stringify(row,(_,v)=>Buffer.isBuffer(v)?v.toString('hex'):v))]));
async function seeded(options={}){const dir=await mkdtemp(path.join(tmpdir(),'viq-clean-slate-')),file=path.join(dir,'db.sqlite'),store=new Store(file,options);await store.init();await store.bootstrapCoordinator({id:'coord',name:'Coordinator'});await store.createActor({id:'worker',name:'Worker',kind:'agent'});const pairing=await store.createPairingCode('coord',{intended_kind:'worker',actor_id:'worker',device_id:'worker-device',device_name:'Worker Device'});await store.pairDevice({code:pairing.code,id:'worker-device',name:'Worker Device'});await store.openWorkerSession('worker-device');for(const key of ['OPEN','WORK','WAIT','DONE','ARCH','DELETED'])await store.createProject(key);for(const key of ['OPEN','WORK','WAIT','DONE','ARCH','DELETED'])await store.createTicket({project:key,title:key,actor:'coord',assignment:'Human'});await store.setTicketState('WORK-1',{state:'Working',actor:'coord'});await store.setTicketState('WAIT-1',{state:'Waiting',actor:'coord'});await store.setTicketState('DONE-1',{state:'Done',actor:'coord'});await store.archiveTicket('ARCH-1',{actor:'coord'});await store.deleteTicket('DELETED-1',{actor:'coord',confirmed:true});const db=new DatabaseSync(file);db.exec("INSERT INTO ticket_blocks(id,ticket_id,created_by,reason,status,created_at) VALUES('block','OPEN-1','coord','x','open',1); INSERT INTO questions(id,ticket_id,asked_by,target_type,target_id,kind,text,status,created_at) VALUES('question','OPEN-1','coord','actor','coord','text','x','open',1); INSERT INTO submission_authority(request_id,ticket_id,actor,device_id,session_id,claim_id,claim_token_hash,generation,question_id,submitted_event_id,question_event_id,created_at) VALUES('request','OPEN-1','coord','coord','session','claim',x'01',1,'question',1,1,1)");db.close();return{dir,file,store};}

test('typed clean slate physically removes every project/ticket row and preserves identity/auth state',async()=>{const f=await seeded();const db=new DatabaseSync(f.file),beforeIdentity=identity(db);db.close();const result=await f.store.cleanSlateProjectsAndTickets();assert.equal(result.success,true);assert.ok(result.removed.events>0);assert.deepEqual(await f.store.listProjects(),[]);assert.deepEqual(await f.store.listBoardTickets(),[]);const after=new DatabaseSync(f.file);assert.deepEqual(counts(after),{projects:0,tickets:0,claims:0,questions:0,ticket_blocks:0,ticket_tombstones:0,submission_authority:0,ticket_projects:0});assert.deepEqual(identity(after),beforeIdentity);assert.equal(after.prepare('SELECT count(*) n FROM events WHERE ticket_id IS NOT NULL OR project IS NOT NULL').get().n,0);assert.ok(after.prepare('SELECT count(*) n FROM events').get().n>0);after.close();await f.store.close()});

test('confirmation is exact, public HTTP cannot invoke cleanup, and output is value-free',async()=>{const f=await seeded(),socket=path.join(f.dir,'operator.sock'),operator=await createOperatorServer({store:f.store,socketPath:socket}),app=await createApp({storage:f.file});await listen(app);try{for(const payload of [{},{confirm:'wrong'},{confirm:'FULL_PROJECT_TICKET_CLEAN_SLATE',extra:true}])assert.equal((await post(socket,payload)).status,409);assert.equal((await f.store.listProjects()).length,6);await assert.rejects(runOperatorCommand(['projects-tickets','clean-slate']));await assert.rejects(runOperatorCommand(['projects-tickets','clean-slate','--confirm','wrong']));const publicResponse=await fetch(`http://127.0.0.1:${app.address().port}/v1/operator/projects-tickets/clean-slate`,{method:'POST',body:'{}'});assert.equal(publicResponse.status,401);const result=await runOperatorCommand(['projects-tickets','clean-slate','--confirm','FULL_PROJECT_TICKET_CLEAN_SLATE'],{socketPath:socket});assert.equal(result.success,true);const serialized=JSON.stringify(result);assert.doesNotMatch(serialized,/token|credential|capability|hash|code/i)}finally{await close(operator);await close(app);await f.store.close()}});

test('injected mid-cleanup failure rolls back data and immutable guards atomically',async()=>{const f=await seeded();await f.store.close();const before=new DatabaseSync(f.file),beforeCounts=counts(before),beforeEvents=before.prepare('SELECT count(*) n FROM events').get().n;before.close();const failing=new Store(f.file,{cleanSlateFailure:()=>{throw new Error('injected cleanup failure')}});await failing.init();await assert.rejects(failing.cleanSlateProjectsAndTickets(),/injected cleanup failure/);const after=new DatabaseSync(f.file);assert.deepEqual(counts(after),beforeCounts);assert.equal(after.prepare('SELECT count(*) n FROM events').get().n,beforeEvents);assert.equal(after.prepare("SELECT count(*) n FROM sqlite_schema WHERE type='trigger' AND name IN ('submission_authority_immutable_delete','ticket_tombstones_immutable_delete','events_immutable_delete','tickets_audit_preserved')").get().n,4);after.close();await failing.close()});
