import assert from 'node:assert/strict';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { Store } from '../src/store.js';
import { createApp } from '../src/server.js';
async function request(base,token,method,route,body){const response=await fetch(`${base}${route}`,{method,headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})},body:body===undefined?undefined:JSON.stringify(body)});const text=await response.text();return{status:response.status,body:text?JSON.parse(text):null}}
async function pairedFixture(){const dir=await mkdtemp(path.join(tmpdir(),'viq-http-')),file=path.join(dir,'data.sqlite');let store=new Store(file);await store.init();const coord=await store.bootstrapCoordinator({id:'maks',name:'Maks'});const tokens={maks:coord.credential};for(const id of['worker-a','worker-b']){const p=await store.createPairingCode('maks',{intended_kind:'worker'});tokens[id]=(await store.pairDevice({code:p.code,id,name:id})).credential}await store.close();const app=await createApp({storage:file});await new Promise(r=>app.listen(0,'127.0.0.1',r));return{app,base:`http://127.0.0.1:${app.address().port}`,tokens}}
const identity=claim=>({claim_id:claim.ticket.claim.claim_id,generation:claim.ticket.claim.generation,claim_token:claim.claim_token});
test('HTTP paired lifecycle preserves claim fencing, submit, accept, and reopen',async t=>{const f=await pairedFixture();t.after(()=>f.app.close());await request(f.base,f.tokens.maks,'POST','/v1/projects',{key:'ABC'});await request(f.base,f.tokens.maks,'POST','/v1/tickets',{project:'ABC',title:'HTTP tracer',assignment:'Agent'});const claim=await request(f.base,f.tokens['worker-a'],'POST','/v1/tickets/ABC-1/claim',{});const credentials=identity(claim.body);assert.equal((await request(f.base,f.tokens['worker-a'],'POST','/v1/tickets/ABC-1/verify',credentials)).status,200);assert.equal((await request(f.base,f.tokens['worker-a'],'POST','/v1/tickets/ABC-1/events',{...credentials,message:'working'})).body.event.type,'progress');await request(f.base,f.tokens.maks,'POST','/v1/roles',{id:'reviewer',name:'Reviewer'});await request(f.base,f.tokens.maks,'PUT','/v1/devices/maks/roles/reviewer',{});const submitted=await request(f.base,f.tokens['worker-a'],'POST','/v1/tickets/ABC-1/submit',{...credentials,reviewer:{type:'role',id:'reviewer'},message:'done'});assert.equal(submitted.body.ticket.state,'Waiting');assert.equal((await request(f.base,f.tokens.maks,'POST','/v1/tickets/ABC-1/accept',{})).body.ticket.state,'Done');assert.equal((await request(f.base,f.tokens.maks,'POST','/v1/tickets/ABC-1/reopen',{})).body.ticket.state,'Open')});
test('HTTP Agent assignment launches while workers cannot mutate assignment',async t=>{const f=await pairedFixture();t.after(()=>f.app.close());await request(f.base,f.tokens.maks,'POST','/v1/projects',{key:'ABC'});await request(f.base,f.tokens.maks,'POST','/v1/tickets',{project:'ABC',title:'Assigned',assignment:'Agent'});assert.equal((await request(f.base,f.tokens['worker-a'],'POST','/v1/tickets/claim-next',{project:'ABC'})).status,200);assert.equal((await request(f.base,f.tokens['worker-a'],'PATCH','/v1/tickets/ABC-1',{assignment:'Human'})).status,403);assert.equal((await request(f.base,null,'GET','/v1/projects')).status,401)});
test('HTTP direct claim shares category predicate and takeover route is absent',async t=>{const f=await pairedFixture();t.after(()=>f.app.close());await request(f.base,f.tokens.maks,'POST','/v1/projects',{key:'ABC'});await request(f.base,f.tokens.maks,'POST','/v1/tickets',{project:'ABC',title:'claim',assignment:'Agent'});const old=await request(f.base,f.tokens['worker-a'],'POST','/v1/tickets/ABC-1/claim',{});assert.equal((await request(f.base,f.tokens.maks,'POST','/v1/tickets/ABC-1/takeover',{})).status,404);assert.equal((await request(f.base,f.tokens['worker-a'],'POST','/v1/tickets/ABC-1/release',identity(old.body))).body.ticket.claim,null)});
test('HTTP coordinator history, immutable project, archive, restore, notes, and delete remain explicit',async t=>{const f=await pairedFixture();t.after(()=>f.app.close());for(const key of['ABC','XYZ'])await request(f.base,f.tokens.maks,'POST','/v1/projects',{key});await request(f.base,f.tokens.maks,'POST','/v1/tickets',{project:'ABC',title:'History',assignment:'Agent'});assert.equal((await request(f.base,f.tokens.maks,'PATCH','/v1/tickets/ABC-1',{project:'XYZ'})).body.error.code,'immutable_project');const edited=await request(f.base,f.tokens.maks,'PATCH','/v1/tickets/ABC-1',{title:'Edited',description:'body',assignment:'Human'});assert.equal(edited.body.ticket.project,'ABC');assert.equal((await request(f.base,f.tokens.maks,'POST','/v1/tickets/ABC-1/notes',{message:'Human note'})).body.event.actor,'maks');await request(f.base,f.tokens.maks,'POST','/v1/tickets/ABC-1/archive',{});await request(f.base,f.tokens.maks,'POST','/v1/tickets/ABC-1/restore',{});assert.equal((await request(f.base,f.tokens.maks,'POST','/v1/tickets/ABC-1/delete',{confirmed:false})).status,409);assert.ok((await request(f.base,f.tokens.maks,'POST','/v1/tickets/ABC-1/delete',{confirmed:true})).body.ticket.deleted_at)});
test('HTTP rejects malformed JSON after paired authentication',async t=>{const f=await pairedFixture();t.after(()=>f.app.close());const malformed=await fetch(`${f.base}/v1/projects`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${f.tokens.maks}`},body:'{'});assert.equal(malformed.status,400);assert.equal((await malformed.json()).error.code,'invalid_json')});
