import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { createHash, generateKeyPairSync, sign } from 'node:crypto';
import { AuthStore, b64url, proofRecord } from '../src/phone-auth-store.js';

const origin='https://phone.test';
const hash=v=>createHash('sha256').update(v).digest();
let clock=1_700_000_000_000;
async function setup(){const dir=await mkdtemp(path.join(os.tmpdir(),'viq-multi-')),store=await new AuthStore(path.join(dir,'auth.sqlite'),{origin,now:()=>clock}).init();return{dir,store}}
async function close(f){f.store.close();await rm(f.dir,{recursive:true,force:true})}
function redeem(store,code,label){const {publicKey,privateKey}=generateKeyPairSync('ec',{namedCurve:'P-256'}),jwk=publicKey.export({format:'jwk'}),device='dev_'+b64url(crypto.getRandomValues(new Uint8Array(18))),result=store.redeemCode({code,device_id:device,label,public_key:{kty:'EC',crv:'P-256',x:jwk.x,y:jwk.y}});return{device,privateKey,...result}}
function prove(store,d,method='GET',target='/v1/actors',body=Buffer.alloc(0)){const c=store.challenge({device_id:d.device,method,target,body_hash:b64url(hash(body))}),record=proofRecord(origin,c.id,Buffer.from(c.nonce,'base64url'),d.device,c.epoch,method,target,hash(body));return{...c,device_id:d.device,signature:b64url(sign(null,record,{key:d.privateKey,dsaEncoding:'ieee-p1363'})),method,target,body}}

test('pairing a second device preserves authorization for the first',async()=>{clock=1_700_000_000_000;const f=await setup();try{const a=redeem(f.store,f.store.createCode('Desk').code),b=redeem(f.store,f.store.createCode('Phone').code);assert.equal(f.store.authorize(prove(f.store,a)),true);assert.equal(f.store.authorize(prove(f.store,b)),true);assert.deepEqual(f.store.listDevices().map(x=>x.label).sort(),['Desk','Phone'])}finally{await close(f)}});
test('six digit code expires and fails when wrong or already used',async()=>{clock=1_700_000_000_000;const f=await setup();try{const minted=f.store.createCode();assert.match(minted.code,/^\d{6}$/);assert.equal(minted.expires,clock+600000);assert.deepEqual(f.store.db.prepare('PRAGMA table_info(pair_codes)').all().map(x=>x.name),['code_hash','label','created','expires','consumed']);assert.equal(f.store.db.prepare('SELECT length(code_hash) n FROM pair_codes').get().n,32);assert.throws(()=>redeem(f.store,'999999'),/authorization failed/);const d=redeem(f.store,minted.code);assert.throws(()=>redeem(f.store,minted.code),/authorization failed/);f.store.createCode();const expired=f.store.createCode();clock=expired.expires;assert.throws(()=>redeem(f.store,expired.code),/authorization failed/);assert.ok(d.device)}finally{await close(f)}});
test('individual revoke leaves the other device active',async()=>{clock=1_700_000_000_000;const f=await setup();try{const a=redeem(f.store,f.store.createCode('A').code),b=redeem(f.store,f.store.createCode('B').code);assert.equal(f.store.revokeDevice(a.device),true);assert.throws(()=>f.store.challenge({device_id:a.device,method:'GET',target:'/v1/x',body_hash:b64url(hash(''))}),/authorization failed/);assert.equal(f.store.authorize(prove(f.store,b)),true);assert.equal(f.store.listDevices().find(x=>x.id===a.device).active,false)}finally{await close(f)}});
test('migration preserves an active epoch-2 device and adds multi-device metadata',async()=>{clock=1_700_000_000_000;const dir=await mkdtemp(path.join(os.tmpdir(),'viq-auth-migrate-')),file=path.join(dir,'auth.sqlite'),db=new DatabaseSync(file);db.exec(`CREATE TABLE intents(id TEXT PRIMARY KEY, verifier BLOB NOT NULL CHECK(length(verifier)=32), origin TEXT NOT NULL, expires INTEGER NOT NULL, consumed INTEGER) STRICT;CREATE TABLE devices(id TEXT PRIMARY KEY,jwk TEXT NOT NULL,epoch INTEGER NOT NULL,active INTEGER NOT NULL CHECK(active IN(0,1)),created INTEGER NOT NULL,revoked INTEGER) STRICT;CREATE UNIQUE INDEX one_active_device ON devices(active) WHERE active=1;CREATE TABLE challenges(id TEXT PRIMARY KEY,device_id TEXT NOT NULL,epoch INTEGER NOT NULL,nonce BLOB NOT NULL CHECK(length(nonce)=32),method TEXT NOT NULL,target TEXT NOT NULL,body_hash BLOB NOT NULL CHECK(length(body_hash)=32),expires INTEGER NOT NULL,consumed INTEGER,FOREIGN KEY(device_id) REFERENCES devices(id)) STRICT;CREATE TABLE audit(seq INTEGER PRIMARY KEY AUTOINCREMENT,at INTEGER NOT NULL,action TEXT NOT NULL,device_id TEXT,detail TEXT NOT NULL) STRICT;`);const {publicKey}=generateKeyPairSync('ec',{namedCurve:'P-256'});db.prepare('INSERT INTO devices VALUES(?,?,2,1,?,NULL)').run('legacy_device_0001',JSON.stringify(publicKey.export({format:'jwk'})),clock-1);db.close();const store=await new AuthStore(file,{origin,now:()=>clock}).init();try{const row=store.listDevices()[0];assert.equal(row.id,'legacy_device_0001');assert.equal(row.epoch,2);assert.equal(row.active,true);assert.equal(row.label,null);assert.equal(row.last_used,null);redeem(store,store.createCode().code);assert.equal(store.listDevices().filter(x=>x.active).length,2)}finally{store.close();await rm(dir,{recursive:true,force:true})}});
test('paired and unpaired markup expose creation and redemption controls',async()=>{const {readFile}=await import('node:fs/promises'),[html,js]=await Promise.all([readFile('web/phone-index.html','utf8'),readFile('web/phone-bootstrap.js','utf8')]);for(const id of ['pair-code','pair-label','redeem-code','add-device','device-list'])assert.match(html,new RegExp(`id="${id}"`));assert.match(js,/create pairing code/i);assert.match(js,/redeem/i);assert.match(js,/10 minutes/i)});
