import assert from 'node:assert/strict';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { Store } from '../src/store.js';
import { createApp } from '../src/server.js';
import { ViqWorkerRuntime } from '../extensions/viq-worker/worker-runtime.mjs';

async function fixture(t){const dir=await mkdtemp(path.join(tmpdir(),'viq-native-poll-')),db=path.join(dir,'db.sqlite'),store=new Store(db);await store.init();const coordinator=await store.bootstrapCoordinator({id:'coord',name:'Coordinator'});await store.createActor({id:'worker',name:'Native Pi',kind:'agent'});const code=await store.createPairingCode('coord',{intended_kind:'worker',actor_id:'worker',device_id:'native-pi',device_name:'Native Pi'});const paired=await store.pairDevice({code:code.code});await store.createProject('ABC');await store.createTicket({project:'ABC',title:'A',assignment:'Agent'});await store.createTicket({project:'ABC',title:'B',assignment:'Agent'});await store.close();const app=await createApp({storage:db});await new Promise(r=>app.listen(0,'127.0.0.1',r));t.after(()=>app.close());return{base:`http://127.0.0.1:${app.address().port}`,credential:paired.credential,coordinator}}

test('native poll is single-flight, heartbeats waiting/working, and requires a fresh runtime after terminal settlement',async t=>{const f=await fixture(t),prompts=[],first=new ViqWorkerRuntime({baseUrl:f.base,credential:f.credential,pollMs:100000,deliver:async prompt=>prompts.push(prompt)});await first.start();assert.equal(first.status().ticket,'ABC-2');assert.equal(prompts.length,1);await first.poll();assert.equal(prompts.length,1);const machines=await fetch(`${f.base}/v1/machines`,{headers:{authorization:`Bearer ${f.coordinator.credential}`}}).then(r=>r.json());assert.deepEqual(machines.machines.find(m=>m.id==='native-pi').state,'working');assert.equal(machines.machines.find(m=>m.id==='native-pi').ticket_id,'ABC-2');assert.equal((await first.settled()).active,true);await first.submit({summary:'done',evidence:['urn:sha256:done']});assert.equal(first.status().rotation_required,true);const second=new ViqWorkerRuntime({baseUrl:f.base,credential:f.credential,pollMs:100000,deliver:async prompt=>prompts.push(prompt)});await second.start();assert.equal(second.status().ticket,'ABC-1');assert.equal(prompts.length,2);assert.match(prompts[0],/"id": "ABC-2"/);assert.match(prompts[1],/"id": "ABC-1"/);await second.stop()});

test('worker presence rejects stale fenced ticket heartbeat',async t=>{const f=await fixture(t),runtime=new ViqWorkerRuntime({baseUrl:f.base,credential:f.credential,pollMs:100000});await runtime.start();const bad=await fetch(`${f.base}/v1/workers/heartbeat`,{method:'POST',headers:{authorization:`Bearer ${f.credential}`,'x-viq-session-capability':'bad','content-type':'application/json'},body:JSON.stringify({mode:'working',ticket_id:'ABC-2',claim_id:'bad',generation:99,claim_token:'bad'})});assert.equal(bad.status,409);await runtime.stop()});
