import assert from 'node:assert/strict';
import { chmod, lstat, mkdir, mkdtemp, readFile, stat, symlink, writeFile } from 'node:fs/promises';
import http from 'node:http';
import { spawnSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { runOperatorCommand } from '../src/operator-cli.js';
import { createOperatorServer } from '../src/operator-server.js';
import { createApp } from '../src/server.js';
import { Store } from '../src/store.js';
const listen=s=>new Promise(r=>s.listen(0,'127.0.0.1',r));const close=s=>new Promise(r=>s.close(r));
async function fixture({now}={}){const dir=await mkdtemp(path.join(tmpdir(),'viq-operator-')),db=path.join(dir,'db.sqlite'),socket=path.join(dir,'operator.sock'),store=new Store(db,{now});await store.init();await store.bootstrapCoordinator({id:'coord',name:'Coordinator'});const operator=await createOperatorServer({store,socketPath:socket}),app=await createApp({storage:db,now});await listen(app);return{dir,db,socket,store,operator,app,base:`http://127.0.0.1:${app.address().port}`,async close(){await close(operator);await close(app);await store.close()}}}
async function pair(f,bundle){const response=await fetch(f.base+'/v1/browsers/pair',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code:bundle.code})});return{status:response.status,body:await response.json()}}

test('real Unix operator CLI emits exact tuple consumed once by ordinary public pairing',async()=>{const f=await fixture();try{const output=path.join(f.dir,'handoff.json'),result=await runOperatorCommand(['pairing','create','--kind','browser','--name','Maks Browser','--output',output],{socketPath:f.socket}),bundle=JSON.parse(await readFile(output,'utf8'));assert.deepEqual(Object.keys(bundle).sort(),['code','device_id','device_name','expires_at']);assert.equal(bundle.device_name,'Maks Browser');assert.match(bundle.device_id,/^browser-[0-9a-f]{24}$/);assert.equal((await stat(output)).mode&0o777,0o600);assert.equal(JSON.stringify(result).includes(bundle.code),false);const bypass=await fetch(f.base+'/v1/devices/pair',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code:bundle.code})});assert.equal((await bypass.json()).error.code,'pairing_kind_mismatch');const accepted=await pair(f,bundle);assert.equal(accepted.status,201);assert.equal(accepted.body.device.id,bundle.device_id);assert.equal(accepted.body.device.kind,'coordinator');assert.equal((await pair(f,bundle)).body.error.code,'pairing_code_used_or_invalid')}finally{await f.close()}});

test('operator pairing expires and public TCP has no operator route',async()=>{let clock=1000;const f=await fixture({now:()=>clock});try{const output=path.join(f.dir,'expires.json');await runOperatorCommand(['pairing','create','--kind','browser','--name','Expiry Browser','--output',output],{socketPath:f.socket});const bundle=JSON.parse(await readFile(output));clock=bundle.expires_at;assert.equal((await pair(f,bundle)).body.error.code,'pairing_code_expired');const publicResult=await fetch(f.base+'/v1/operator/browser-pairings',{method:'POST',headers:{'content-type':'application/json'},body:'{"name":"no"}'});assert.equal(publicResult.status,401);assert.equal(JSON.stringify(bundle).includes('credential'),false)}finally{await f.close()}});

test('socket is 0600, safe stale socket is replaced, and unsafe paths fail closed',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'viq-socket-')),db=path.join(dir,'db'),store=new Store(db);await store.init();await store.bootstrapCoordinator({id:'coord',name:'Coordinator'});const socket=path.join(dir,'operator.sock');let server=await createOperatorServer({store,socketPath:socket});assert.equal((await lstat(socket)).isSocket(),true);assert.equal((await stat(socket)).mode&0o777,0o600);if(process.geteuid?.()===0){const probe=spawnSync(process.execPath,['-e',`require('http').get({socketPath:process.argv[1],path:'/'},()=>process.exit(2)).on('error',()=>process.exit(0))`,socket],{uid:65534,gid:65534});assert.equal(probe.status,0)}await close(server);const stale=http.createServer();await new Promise(r=>stale.listen(socket,r));await new Promise(r=>stale.close(r));server=await createOperatorServer({store,socketPath:socket});await close(server);await writeFile(socket,'not a socket',{mode:0o600});await assert.rejects(createOperatorServer({store,socketPath:socket}),/unsafe existing/);await writeFile(path.join(dir,'target'),'x');await symlink(path.join(dir,'target'),path.join(dir,'link.sock'));await assert.rejects(createOperatorServer({store,socketPath:path.join(dir,'link.sock')}),/unsafe existing/);const open=path.join(dir,'open');await mkdir(open,{mode:0o777});await chmod(open,0o777);await assert.rejects(createOperatorServer({store,socketPath:path.join(open,'x.sock')}),/unsafe operator socket directory/);await store.close()});

test('CLI validates narrow options, redacts failures, and never overwrites output',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'viq-cli-deny-')),output=path.join(dir,'out');for(const args of[['pairing','create','--kind','worker','--name','x','--output',output],['pairing','create','--kind','browser','--name','bad\nname','--output',output],['pairing','create','--kind','browser','--name','x','--output',output,'--server','http://evil']])await assert.rejects(runOperatorCommand(args));await writeFile(output,'keep',{mode:0o600});let called=false;await assert.rejects(runOperatorCommand(['pairing','create','--kind','browser','--name','x','--output',output],{request:async()=>{called=true}}),e=>e.code==='EEXIST');assert.equal(called,false);assert.equal(await readFile(output,'utf8'),'keep');const other=path.join(dir,'other'),secret='never-print-this-code';await assert.rejects(runOperatorCommand(['pairing','create','--kind','browser','--name','x','--output',other],{request:async()=>({code:secret,device_id:'id',device_name:'wrong',expires_at:1})}),e=>!e.message.includes(secret));await assert.rejects(stat(other),e=>e.code==='ENOENT')});
