import assert from 'node:assert/strict';
import { chmod, link, mkdtemp, readFile, stat, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { readOperatorCredential, runOperatorCommand } from '../src/operator-cli.js';

async function fixture(){const dir=await mkdtemp(path.join(tmpdir(),'viq-operator-')),credential=path.join(dir,'operator.credential'),output=path.join(dir,'handoff.json');await writeFile(credential,'coord.test-secret-that-is-long-enough\n',{mode:0o600});return{dir,credential,output}}
class Client { constructor(options){this.options=options;Client.instances.push(this)} async request(method,route,body){Client.calls.push({method,route,body});if(route==='/v1/devices/me')return{device:{kind:'coordinator'},actor:{id:'human-admin',admin:true}};return{...body,code:'server-issued-code',expires_at:1700000900000}} }
Client.instances=[];Client.calls=[];
const args=f=>['pairing','create','--kind','browser','--name','Maks browser','--output',f.output,'--credential-file',f.credential,'--server','http://127.0.0.1:17373'];

test('typed operator command uses only authenticated core routes and writes a code-only 0600 handoff',async()=>{const f=await fixture();Client.calls=[];Client.instances=[];const result=await runOperatorCommand(args(f),{Client});assert.equal(result.output,f.output);assert.deepEqual(Client.calls.map(x=>[x.method,x.route]),[['GET','/v1/devices/me'],['POST','/v1/pairing-codes']]);assert.deepEqual(Client.calls[1].body,{intended_kind:'coordinator',actor_id:'human-admin',device_id:Client.calls[1].body.device_id,device_name:'Maks browser',ttl_ms:900000});assert.match(Client.calls[1].body.device_id,/^browser-[0-9a-f]{24}$/);assert.deepEqual(JSON.parse(await readFile(f.output,'utf8')),{code:'server-issued-code',expires_at:1700000900000});assert.equal((await stat(f.output)).mode&0o777,0o600);assert.equal(Client.instances[0].options.deviceToken,'coord.test-secret-that-is-long-enough');assert.equal(JSON.stringify(result).includes('server-issued-code'),false)});

test('operator command rejects nonlocal servers, worker kind, overwrite, and inconsistent binding',async()=>{const f=await fixture();for(const replace of[['browser','worker'],['http://127.0.0.1:17373','https://viq.makscee.ru']]){const attempt=args(f).map(x=>x===replace[0]?replace[1]:x);await assert.rejects(runOperatorCommand(attempt,{Client}))}await writeFile(f.output,'keep',{mode:0o600});await assert.rejects(runOperatorCommand(args(f),{Client}),e=>e.code==='EEXIST');assert.equal(await readFile(f.output,'utf8'),'keep');class Bad extends Client{async request(method,route,body){const value=await super.request(method,route,body);return route==='/v1/pairing-codes'?{...value,intended_kind:'worker'}:value}}const other={...f,output:path.join(f.dir,'other')};await assert.rejects(runOperatorCommand(args(other),{Client:Bad}),e=>e.code==='operator_invalid_response');await assert.rejects(stat(other.output),e=>e.code==='ENOENT');
});

test('credential reader fails closed on permissions, links, symlinks, and malformed content',async()=>{const f=await fixture();assert.equal(readOperatorCredential(f.credential),'coord.test-secret-that-is-long-enough');await chmod(f.credential,0o640);assert.throws(()=>readOperatorCredential(f.credential),/unsafe/);await chmod(f.credential,0o600);await link(f.credential,path.join(f.dir,'hard'));assert.throws(()=>readOperatorCredential(f.credential),/unsafe/);const target=path.join(f.dir,'target');await writeFile(target,'coord.another-secret-that-is-long-enough\n',{mode:0o600});const alias=path.join(f.dir,'alias');await symlink(target,alias);assert.throws(()=>readOperatorCredential(alias));const malformed=path.join(f.dir,'malformed');await writeFile(malformed,'this contains whitespace and is definitely long enough\n',{mode:0o600});assert.throws(()=>readOperatorCredential(malformed),/malformed/)});
