import assert from 'node:assert/strict';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { DatabaseSync } from 'node:sqlite';
import { Store } from '../src/store.js';
import { createApp } from '../src/server.js';
import { HttpApplicationClient } from '../src/http-client.js';

async function fixture({now}={}){const dir=await mkdtemp(path.join(tmpdir(),'viq-pairing-poc-')),db=path.join(dir,'db.sqlite');let store=new Store(db,{now});await store.init();const coordinator=await store.bootstrapCoordinator({id:'coord',name:'Coordinator'});await store.close();const app=await createApp({storage:db,now});await new Promise(r=>app.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${app.address().port}`;const req=async(token,method,route,body)=>{const r=await fetch(base+route,{method,headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})},body:body===undefined?undefined:JSON.stringify(body)});const text=await r.text();return{status:r.status,body:text?JSON.parse(text):null}};const pair=async(kind,id)=>{const code=await req(coordinator.credential,'POST','/v1/pairing-codes',{intended_kind:kind,ttl_ms:10000});const paired=await req(null,'POST','/v1/devices/pair',{code:code.body.code,id,name:id});return{...paired.body,code:code.body.code}};return{app,base,db,req,pair,coordinator}}

test('clean PoC schema omits execution authorities while an existing rollback table is preserved unused',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'viq-pair-schema-')),file=path.join(dir,'db.sqlite');let store=new Store(file);await store.init();await store.close();let db=new DatabaseSync(file);assert.equal(db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='execution_authorities'").get(),undefined);db.exec('CREATE TABLE execution_authorities(id INTEGER PRIMARY KEY) STRICT');db.close();store=new Store(file);await store.init();await store.close();db=new DatabaseSync(file,{readOnly:true});assert.ok(db.prepare("SELECT 1 ok FROM sqlite_master WHERE type='table' AND name='execution_authorities'").get().ok);db.close()});

test('one-time pairing is code-authorized and rejects used, expired, inactive-issuer, unpaired, and revoked credentials',async t=>{let clock=1000;const f=await fixture({now:()=>clock});t.after(()=>f.app.close());const worker=await f.pair('worker','worker-a');assert.equal(worker.device.kind,'worker');const replay=await f.req(null,'POST','/v1/devices/pair',{code:worker.code,id:'replay',name:'Replay'});assert.equal(replay.body.error.code,'pairing_code_used_or_invalid');const exp=await f.req(f.coordinator.credential,'POST','/v1/pairing-codes',{intended_kind:'worker',ttl_ms:1000});clock+=1001;assert.equal((await f.req(null,'POST','/v1/devices/pair',{code:exp.body.code,id:'late',name:'Late'})).body.error.code,'pairing_code_expired');assert.equal((await f.req('unpaired.invalid','GET','/v1/projects')).body.error.code,'device_unauthorized');const workerCode=await f.req(f.coordinator.credential,'POST','/v1/pairing-codes',{intended_kind:'worker'});assert.equal((await f.req(worker.credential,'POST','/v1/devices/pair',{code:workerCode.body.code,id:'worker-header',name:'Worker Header'})).status,201);const invalidHeaderCode=await f.req(f.coordinator.credential,'POST','/v1/pairing-codes',{intended_kind:'worker'});assert.equal((await f.req('invalid.bearer','POST','/v1/devices/pair',{code:invalidHeaderCode.body.code,id:'invalid-header',name:'Invalid Header'})).status,201);const replacementCode=await f.req(f.coordinator.credential,'POST','/v1/pairing-codes',{intended_kind:'coordinator'});const replacement=await f.req(null,'POST','/v1/devices/pair',{code:replacementCode.body.code,id:'coord-b',name:'Coordinator B'});const orphanCode=await f.req(f.coordinator.credential,'POST','/v1/pairing-codes',{intended_kind:'coordinator'});await f.req(replacement.body.credential,'POST','/v1/devices/coord/revoke',{});assert.equal((await f.req(null,'POST','/v1/devices/pair',{code:orphanCode.body.code,id:'orphan',name:'Orphan'})).body.error.code,'pairing_code_used_or_invalid');assert.equal((await f.req(worker.credential,'GET','/v1/projects')).status,200);await f.req(replacement.body.credential,'POST','/v1/devices/worker-a/revoke',{});assert.equal((await f.req(worker.credential,'GET','/v1/projects')).body.error.code,'device_revoked')});

test('hard-coded coordinator/worker permissions and role-only assignment eligibility',async t=>{const f=await fixture();t.after(()=>f.app.close());const worker=await f.pair('worker','worker-a'),other=await f.pair('worker','worker-b');await f.req(f.coordinator.credential,'POST','/v1/projects',{key:'DOG'});await f.req(f.coordinator.credential,'POST','/v1/roles',{id:'tower-pi',name:'Tower Pi'});await f.req(f.coordinator.credential,'PUT','/v1/devices/worker-a/roles/tower-pi',{});for(const [method,route,body]of[['POST','/v1/pairing-codes',{intended_kind:'worker'}],['POST','/v1/roles',{id:'bad',name:'Bad'}],['PUT','/v1/devices/worker-b/roles/tower-pi',{}],['POST','/v1/tickets',{project:'DOG',title:'Bad',assignee:{type:'device',id:'worker-a'}}]])assert.equal((await f.req(worker.credential,method,route,body)).status,403);await f.req(f.coordinator.credential,'POST','/v1/tickets',{project:'DOG',title:'Unassigned'});await f.req(f.coordinator.credential,'POST','/v1/tickets',{project:'DOG',title:'Other',assignee:{type:'device',id:'worker-b'}});await f.req(f.coordinator.credential,'POST','/v1/tickets',{project:'DOG',title:'Role',assignee:{type:'role',id:'tower-pi'}});const question=await f.req(f.coordinator.credential,'POST','/v1/tickets/DOG-3/human-questions',{text:'Coordinator only answer?',target_type:'device',target_id:'worker-a'});assert.equal((await f.req(worker.credential,'POST',`/v1/tickets/DOG-3/questions/${question.body.question.id}/answer`,{answer:'forbidden'})).status,403);assert.equal((await f.req(worker.credential,'POST','/v1/tickets/DOG-1/claim',{})).body.error.code,'ticket_ineligible');assert.equal((await f.req(worker.credential,'POST','/v1/tickets/DOG-2/claim',{})).body.error.code,'ticket_ineligible');for(const id of['DOG-1','DOG-2'])assert.equal((await f.req(worker.credential,'POST',`/v1/tickets/${id}/claim`,{})).body.error.code,'ticket_ineligible');const claim=await f.req(worker.credential,'POST','/v1/tickets/claim-next',{project:'DOG'});assert.equal(claim.body.ticket.id,'DOG-3');assert.equal((await f.req(other.credential,'GET','/v1/tickets/DOG-3')).status,403);assert.equal((await f.req(worker.credential,'POST','/v1/tickets/DOG-3/accept',{})).status,403)});

test('direct HTTP, claim-next, next, and client all use the same assigned-worker predicate',async t=>{const f=await fixture();t.after(()=>f.app.close());const worker=await f.pair('worker','worker-a');await f.req(f.coordinator.credential,'POST','/v1/projects',{key:'DOG'});for(const title of['One','Two','Three'])await f.req(f.coordinator.credential,'POST','/v1/tickets',{project:'DOG',title,assignee:{type:'device',id:'worker-a'}});const next=await f.req(worker.credential,'GET','/v1/tickets/next?project=DOG');assert.equal(next.body.ticket.id,'DOG-1');const direct=await f.req(worker.credential,'POST','/v1/tickets/DOG-1/claim',{});assert.equal(direct.body.ticket.id,'DOG-1');await f.req(worker.credential,'POST','/v1/tickets/DOG-1/release',{claim_id:direct.body.ticket.claim.claim_id,claim_token:direct.body.claim_token,generation:direct.body.ticket.claim.generation});const client=new HttpApplicationClient({server:f.base,deviceToken:worker.credential});const viaClient=await client.request('POST','/v1/tickets/DOG-1/claim',{});await client.request('POST','/v1/tickets/DOG-1/release',{claim_id:viaClient.ticket.claim.claim_id,claim_token:viaClient.claim_token,generation:viaClient.ticket.claim.generation});const atomic=await client.request('POST','/v1/tickets/claim-next',{project:'DOG'});assert.equal(atomic.ticket.id,'DOG-1')});

test('blocker and active claim uniformly fence every claim ingress',async t=>{const f=await fixture();t.after(()=>f.app.close());const worker=await f.pair('worker','worker-a');await f.req(f.coordinator.credential,'POST','/v1/projects',{key:'DOG'});await f.req(f.coordinator.credential,'POST','/v1/tickets',{project:'DOG',title:'Blocked',assignee:{type:'device',id:'worker-a'}});const claim=await f.req(worker.credential,'POST','/v1/tickets/DOG-1/claim',{});const id={claim_id:claim.body.ticket.claim.claim_id,claim_token:claim.body.claim_token,generation:claim.body.ticket.claim.generation};await f.req(worker.credential,'POST','/v1/tickets/DOG-1/block',{...id,reason:'wait'});await f.req(worker.credential,'POST','/v1/tickets/DOG-1/release',id);assert.equal((await f.req(worker.credential,'POST','/v1/tickets/DOG-1/claim',{})).body.error.code,'ticket_ineligible');assert.equal((await f.req(worker.credential,'POST','/v1/tickets/claim-next',{project:'DOG'})).status,204);assert.equal((await f.req(worker.credential,'GET','/v1/tickets/next?project=DOG')).status,204)});
