import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import net from 'node:net';
import { mkdtemp, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { generateKeyPairSync, createHash, createHmac, sign } from 'node:crypto';
import { createPhoneGateway } from '../src/phone-gateway.js';
import { pairRecord, proofRecord, b64url } from '../src/phone-auth-store.js';

const listen=s=>new Promise(r=>s.listen(0,'127.0.0.1',r));
const close=s=>new Promise(r=>s.close(r));
const sha=x=>createHash('sha256').update(x).digest();
async function setup(){
 const dir=await mkdtemp(path.join(os.tmpdir(),'viq-gw-'));let hits=0,last;const upstreamAuthorization='test_upstream_authority_0001';
 const upstream=http.createServer(async(req,res)=>{hits++;const chunks=[];for await(const c of req)chunks.push(c);last={headers:req.headers,body:Buffer.concat(chunks),url:req.url,method:req.method};res.setHeader('content-type','application/json');res.setHeader('set-cookie','upstream=must-strip');res.end('{"ok":true}')});
 await listen(upstream);const origin='https://phone.test',{port}=upstream.address(),gateway=await createPhoneGateway({authDb:path.join(dir,'auth.sqlite'),origin,upstream:`http://127.0.0.1:${port}`,upstreamAuthorization,testMode:true});await listen(gateway);
 const base=`http://127.0.0.1:${gateway.address().port}`;return{dir,upstream,gateway,base,origin,upstreamAuthorization,get hits(){return hits},get last(){return last}};
}
async function cleanup(f){await close(f.gateway);await close(f.upstream);await rm(f.dir,{recursive:true,force:true})}
function pair(f){const device='dev_'+b64url(crypto.getRandomValues(new Uint8Array(18))),p=f.gateway.authStore.createPair({deviceId:device,actorId:'coordinator',admin:true,label:'Test browser'}),{publicKey,privateKey}=generateKeyPairSync('ec',{namedCurve:'P-256'}),jwk=publicKey.export({format:'jwk'}),v=sha(Buffer.concat([Buffer.from('viq-phone-pair-verifier-v1\0'),Buffer.from(p.code.split('.')[1])])),proof=createHmac('sha256',v).update(pairRecord(f.origin,p.intentId,jwk.x,jwk.y)).digest(),d=f.gateway.authStore.consumePair({intent_id:p.intentId,public_key:{kty:'EC',crv:'P-256',x:jwk.x,y:jwk.y},proof:b64url(proof)});return{device,privateKey,epoch:d.epoch}}
function headers(f,p,method,target,body){const c=f.gateway.authStore.challenge({device_id:p.device,method,target,body_hash:b64url(sha(body))}),rec=proofRecord(f.origin,c.id,Buffer.from(c.nonce,'base64url'),p.device,c.epoch,method,target,sha(body)),sig=sign(null,rec,{key:p.privateKey,dsaEncoding:'ieee-p1363'});return{'x-viq-device':p.device,'x-viq-challenge':c.id,'x-viq-signature':b64url(sig),authorization:'Bearer must-strip',cookie:'must-strip=1',forwarded:'for=bad','x-forwarded-for':'bad'}}
function rawRequest(f,target,{method='GET',headers={},body}={}){return new Promise((resolve,reject)=>{const req=http.request({host:'127.0.0.1',port:f.gateway.address().port,path:target,method,headers},res=>{res.resume();res.on('end',()=>resolve(res))});req.on('error',reject);req.end(body)})}
function rawWire(f,target){return new Promise((resolve,reject)=>{const socket=net.connect(f.gateway.address().port,'127.0.0.1',()=>socket.write(`GET ${target} HTTP/1.1\r\nHost: phone.test\r\nConnection: close\r\n\r\n`));let response='';socket.on('data',c=>response+=c);socket.on('end',()=>resolve(Number(response.match(/^HTTP\/1\.1 (\d+)/)?.[1])));socket.on('error',reject)})}

test('unpaired API is denied before upstream',async()=>{const f=await setup();try{assert.equal((await fetch(f.base+'/v1/x')).status,403);assert.equal(f.hits,0)}finally{await cleanup(f)}});
test('concurrent replay has exactly one winner/upstream request and strips request and response credentials',async()=>{const f=await setup();try{const p=pair(f),body=Buffer.from('{"x":1}'),h=headers(f,p,'POST','/v1/x?q=1',body),rs=await Promise.all([fetch(f.base+'/v1/x?q=1',{method:'POST',headers:h,body}),fetch(f.base+'/v1/x?q=1',{method:'POST',headers:h,body})]);assert.deepEqual(rs.map(x=>x.status).sort(),[200,403]);assert.equal(rs.find(x=>x.status===200).headers.get('set-cookie'),null);assert.equal(f.hits,1);assert.equal(f.last.url,'/v1/x?q=1');assert.equal(f.last.headers.authorization,`Bearer ${f.upstreamAuthorization}`);for(const x of ['cookie','forwarded','x-forwarded-for','x-viq-device','x-viq-challenge','x-viq-signature'])assert.equal(f.last.headers[x],undefined);assert.deepEqual(f.last.body,body)}finally{await cleanup(f)}});
test('signed browser self-revocation is device-scoped and never reaches upstream',async()=>{const f=await setup();try{const a=pair(f),b=pair(f),body=Buffer.alloc(0),h=headers(f,b,'POST','/__phone/revoke',body);assert.equal((await rawRequest(f,'/__phone/revoke',{method:'POST',headers:h,body})).statusCode,200);assert.equal(f.hits,0);assert.equal(f.gateway.authStore.active(b.device),undefined);assert.ok(f.gateway.authStore.active(a.device));assert.equal((await rawRequest(f,'/v1/x',{headers:headers(f,a,'GET','/v1/x',body)})).statusCode,200)}finally{await cleanup(f)}});
test('auth JSON is limited to 8KiB and application bodies to 1MiB',async()=>{const f=await setup();try{assert.equal((await fetch(f.base+'/__phone/challenge',{method:'POST',body:Buffer.alloc(8193)})).status,413);assert.equal((await fetch(f.base+'/health',{method:'POST',body:Buffer.alloc(1048577)})).status,413);assert.equal(f.hits,0)}finally{await cleanup(f)}});
test('body substitution fails before upstream',async()=>{const f=await setup();try{const p=pair(f),h=headers(f,p,'POST','/v1/x',Buffer.from('a'));assert.equal((await fetch(f.base+'/v1/x',{method:'POST',headers:h,body:'b'})).status,403);assert.equal(f.hits,0)}finally{await cleanup(f)}});
test('source IP rate limit cannot be bypassed by unique device ids and state stays bounded',async()=>{const f=await setup();try{const statuses=[];for(let i=0;i<130;i++){const device=`fake_device_${String(i).padStart(16,'0')}`;statuses.push((await fetch(f.base+'/__phone/challenge',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({device_id:device,method:'GET',target:'/v1/x',body_hash:b64url(sha(''))})})).status)}assert.equal(statuses[120],429);assert.ok(statuses.slice(120).every(x=>x===429));assert.ok(f.gateway.rateLimitBuckets.size<=121)}finally{await cleanup(f)}});
test('raw request-target rejects normalization hazards and binds exact target',async()=>{const f=await setup();try{for(const target of ['http://evil.test/health','//evil.test/health','/v1/%2e%2e/health','/v1/x\\health'])assert.equal((await rawRequest(f,target)).statusCode,400,target);assert.equal(await rawWire(f,'/v1/x\x01control'),400);const p=pair(f),body=Buffer.alloc(0),h=headers(f,p,'GET','/v1/x?raw=%41',body);assert.equal((await rawRequest(f,'/v1/x?raw=%41',{headers:h})).statusCode,200);assert.equal(f.last.url,'/v1/x?raw=%41');assert.equal(f.hits,1)}finally{await cleanup(f)}});
test('API fails closed before upstream when confidential handoff authority is absent',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'viq-no-handoff-'));let hits=0;const upstream=http.createServer((_req,res)=>{hits++;res.end()});await listen(upstream);const gateway=await createPhoneGateway({authDb:path.join(dir,'auth.sqlite'),origin:'https://phone.test',upstream:`http://127.0.0.1:${upstream.address().port}`,testMode:true});await listen(gateway);try{assert.equal((await fetch(`http://127.0.0.1:${gateway.address().port}/v1/x`)).status,403);assert.equal(hits,0)}finally{await close(gateway);await close(upstream);await rm(dir,{recursive:true,force:true})}});
test('only fixed public targets pass and unknown non-v1 targets are denied',async()=>{const f=await setup();try{assert.equal((await fetch(f.base+'/health')).status,200);assert.equal((await fetch(f.base+'/health?x=1')).status,404);assert.equal((await fetch(f.base+'/unknown')).status,404);assert.equal((await fetch(f.base+'/app.js')).status,200);assert.equal(f.hits,1)}finally{await cleanup(f)}});
test('TLS configuration requires a complete keypair or explicit termination mode',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'viq-tls-'));const upstream=http.createServer((q,r)=>r.end());await listen(upstream);const options={authDb:path.join(dir,'a.sqlite'),origin:'https://phone.test',upstream:`http://127.0.0.1:${upstream.address().port}`};try{await assert.rejects(createPhoneGateway(options),/TLS/);await assert.rejects(createPhoneGateway({...options,cert:'partial'}),/complete/);const gateway=await createPhoneGateway({...options,tlsTerminated:true});await close(gateway)}finally{await close(upstream);await rm(dir,{recursive:true,force:true})}});
