import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm, chmod, stat } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { generateKeyPairSync, createHmac, createHash, sign } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import { AuthStore, pairRecord, proofRecord, b64url } from '../src/phone-auth-store.js';

const origin='https://phone.test';let clock=1_700_000_000_000;
const hash=value=>createHash('sha256').update(value).digest();
const metadata=(deviceId='dev_'+b64url(crypto.getRandomValues(new Uint8Array(18))))=>({deviceId,actorId:'trusted-coordinator',admin:true,label:'Trusted browser'});
const redemption=(pair,deviceId)=>{const {publicKey,privateKey}=generateKeyPairSync('ec',{namedCurve:'P-256'}),jwk=publicKey.export({format:'jwk'}),secret=pair.code.split('.')[1],verifier=hash(Buffer.concat([Buffer.from('viq-phone-pair-verifier-v1\0'),Buffer.from(secret)]));return{privateKey,body:{intent_id:pair.intentId,public_key:{kty:'EC',crv:'P-256',x:jwk.x,y:jwk.y},proof:b64url(createHmac('sha256',verifier).update(pairRecord(origin,pair.intentId,jwk.x,jwk.y)).digest())},deviceId}};
async function fixture(){const dir=await mkdtemp(path.join(os.tmpdir(),'viq-auth-'));clock=1_700_000_000_000;const store=await new AuthStore(path.join(dir,'auth.sqlite'),{origin,now:()=>clock}).init(),bound=metadata(),pair=store.createPair(bound),redeem=redemption(pair,bound.deviceId);const result=store.consumePair(redeem.body);return{dir,store,device:result.device_id,privateKey:redeem.privateKey}}
async function cleanup(f){f.store.close();await rm(f.dir,{recursive:true,force:true})}
function signed(f,method='GET',target='/v1/actors',body=Buffer.alloc(0)){const challenge=f.store.challenge({device_id:f.device,method,target,body_hash:b64url(hash(body))}),record=proofRecord(origin,challenge.id,Buffer.from(challenge.nonce,'base64url'),f.device,challenge.epoch,method,target,hash(body));return{...challenge,device_id:f.device,signature:b64url(sign(null,record,{key:f.privateKey,dsaEncoding:'ieee-p1363'})),method,target,body}}

test('code-only intent binds device, actor, admin, and label server-side',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'viq-bound-intent-')),store=await new AuthStore(path.join(dir,'auth.sqlite'),{origin,now:()=>clock}).init();try{const bound=metadata('browser_bound_0001'),pair=store.createPair(bound),redeem=redemption(pair,bound.deviceId);assert.match(pair.code,/^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$/);assert.equal(Object.hasOwn(pair,'secret'),false);assert.equal(Object.hasOwn(pair,'url'),false);assert.throws(()=>store.consumePair({...redeem.body,device_id:'caller_substitution'}),/invalid request/);const result=store.consumePair(redeem.body);assert.deepEqual(result,{device_id:bound.deviceId,epoch:1});const row=store.db.prepare('SELECT device_id,actor_id,admin,label FROM intents WHERE id=?').get(pair.intentId);assert.deepEqual({...row},{device_id:bound.deviceId,actor_id:bound.actorId,admin:1,label:bound.label})}finally{store.close();await rm(dir,{recursive:true,force:true})}});
test('unpaired, expired, reused, and revoked requests fail closed',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'viq-fail-')),store=await new AuthStore(path.join(dir,'auth.sqlite'),{origin,now:()=>clock}).init();try{assert.throws(()=>store.challenge({device_id:'missing_device_0001',method:'GET',target:'/v1/x',body_hash:b64url(hash(''))}),/authorization failed/);let bound=metadata(),pair=store.createPair(bound),redeem=redemption(pair,bound.deviceId);clock=pair.expires;assert.throws(()=>store.consumePair(redeem.body),/expired/);clock-=1;bound=metadata();pair=store.createPair(bound);redeem=redemption(pair,bound.deviceId);store.consumePair(redeem.body);assert.throws(()=>store.consumePair(redeem.body),/already used|authorization failed/);store.revoke(bound.deviceId);assert.throws(()=>store.challenge({device_id:bound.deviceId,method:'GET',target:'/v1/x',body_hash:b64url(hash(''))}),/authorization failed/)}finally{store.close();await rm(dir,{recursive:true,force:true})}});
test('request proof is one-use and substitutions fail',async()=>{const f=await fixture();try{const proof=signed(f);assert.equal(f.store.authorize(proof),true);assert.throws(()=>f.store.authorize(proof),/authorization failed/);for(const key of ['method','target','body']){const changed=signed(f);if(key==='method')changed.method='POST';if(key==='target')changed.target='/v1/actors?x=1';if(key==='body')changed.body=Buffer.from('x');assert.throws(()=>f.store.authorize(changed),/authorization failed/)}}finally{await cleanup(f)}});
test('challenge expiry boundary and outstanding limit are enforced',async()=>{const f=await fixture();try{const proof=signed(f);clock=proof.expires;assert.throws(()=>f.store.authorize(proof),/authorization failed/);clock-=1;for(let i=0;i<7;i++)f.store.challenge({device_id:f.device,method:'GET',target:`/v1/${i}`,body_hash:b64url(hash(''))});assert.throws(()=>f.store.challenge({device_id:f.device,method:'GET',target:'/v1/overflow',body_hash:b64url(hash(''))}),/authorization failed/)}finally{await cleanup(f)}});
test('distinct active devices and pending intents coexist while same-device conflicts fail closed',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'viq-multi-')),store=await new AuthStore(path.join(dir,'auth.sqlite'),{origin,now:()=>clock}).init();try{const a=metadata('browser_active_A1'),pa=store.createPair(a),ra=redemption(pa,a.deviceId);store.consumePair(ra.body);const b=metadata('browser_active_B1'),c=metadata('browser_active_C1'),pb=store.createPair(b),pc=store.createPair(c),rb=redemption(pb,b.deviceId),rc=redemption(pc,c.deviceId);assert.equal(store.authorize(signed({store,device:a.deviceId,privateKey:ra.privateKey})),true);store.consumePair(rb.body);store.consumePair(rc.body);assert.throws(()=>store.consumePair(rb.body),/already used|authorization failed/);for(const device of [{meta:a,key:ra.privateKey},{meta:b,key:rb.privateKey},{meta:c,key:rc.privateKey}])assert.equal(store.authorize(signed({store,device:device.meta.deviceId,privateKey:device.key})),true);assert.throws(()=>store.createPair(metadata(b.deviceId)),/active|conflict|already/);const pending=store.createPair(metadata('browser_pending_D1'));assert.throws(()=>store.createPair(metadata('browser_pending_D1')),/pending|conflict|already/);assert.equal(store.db.prepare('SELECT consumed FROM intents WHERE id=?').get(pending.intentId).consumed,null)}finally{store.close();await rm(dir,{recursive:true,force:true})}});
test('device-scoped revoke preserves unrelated devices and target intents',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'viq-revoke-')),store=await new AuthStore(path.join(dir,'auth.sqlite'),{origin,now:()=>clock}).init();try{const devices=[];for(const id of ['browser_revoke_A1','browser_revoke_B1','browser_revoke_C1']){const meta=metadata(id),redeem=redemption(store.createPair(meta),id);store.consumePair(redeem.body);devices.push({meta,key:redeem.privateKey})}const unrelated=store.createPair(metadata('browser_pending_D2'));assert.equal(store.revoke(devices[1].meta.deviceId),true);assert.throws(()=>store.challenge({device_id:devices[1].meta.deviceId,method:'GET',target:'/v1/x',body_hash:b64url(hash(''))}),/authorization failed/);for(const device of [devices[0],devices[2]])assert.equal(store.authorize(signed({store,device:device.meta.deviceId,privateKey:device.key})),true);assert.equal(store.db.prepare('SELECT consumed FROM intents WHERE id=?').get(unrelated.intentId).consumed,null);assert.equal(store.revoke('missing_browser_01'),false)}finally{store.close();await rm(dir,{recursive:true,force:true})}});
test('legacy one-active index migrates idempotently and preserves authorization',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'viq-legacy-auth-')),file=path.join(dir,'auth.sqlite'),key=generateKeyPairSync('ec',{namedCurve:'P-256'});let db=new DatabaseSync(file);db.exec(`CREATE TABLE devices(id TEXT PRIMARY KEY,jwk TEXT NOT NULL,epoch INTEGER NOT NULL,active INTEGER NOT NULL CHECK(active IN(0,1)),created INTEGER NOT NULL,revoked INTEGER,actor_id TEXT NOT NULL,admin INTEGER NOT NULL CHECK(admin IN(0,1)),label TEXT NOT NULL) STRICT;CREATE UNIQUE INDEX one_active_device ON devices(active) WHERE active=1;`);db.prepare('INSERT INTO devices VALUES(?,?,1,1,?,NULL,?,1,?)').run('browser_legacy_A1',JSON.stringify(key.publicKey.export({format:'jwk'})),clock,'trusted-coordinator','Legacy browser');db.close();for(let restart=0;restart<2;restart++){const store=await new AuthStore(file,{origin,now:()=>clock}).init();try{assert.equal(store.db.prepare("SELECT count(*) n FROM sqlite_master WHERE type='index' AND name='one_active_device'").get().n,0);assert.equal(store.authorize(signed({store,device:'browser_legacy_A1',privateKey:key.privateKey})),true);if(restart===0){const b=metadata('browser_legacy_B1'),redeem=redemption(store.createPair(b),b.deviceId);store.consumePair(redeem.body)}}finally{store.close()}}await rm(dir,{recursive:true,force:true})});
test('origin and filesystem permissions stay constrained',async()=>{for(const bad of ['http://phone.test','https://user@phone.test','https://phone.test/path','https://phone.test/'])assert.throws(()=>new AuthStore('/tmp/unused',{origin:bad}),/canonical/);const dir=await mkdtemp(path.join(os.tmpdir(),'viq-mode-'));await chmod(dir,0o751);const file=path.join(dir,'auth.sqlite'),store=await new AuthStore(file,{origin}).init();try{assert.equal((await stat(dir)).mode&0o777,0o751);assert.equal((await stat(file)).mode&0o777,0o600)}finally{store.close();await rm(dir,{recursive:true,force:true})}});
