import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import os from 'node:os';
import path from 'node:path';
import { mkdtemp, rm } from 'node:fs/promises';
import { createHash, createHmac, generateKeyPairSync, sign } from 'node:crypto';
import { createPhoneGateway } from '../src/phone-gateway.js';
import { b64url, pairRecord, proofRecord } from '../src/phone-auth-store.js';

const listen=s=>new Promise(r=>s.listen(0,'127.0.0.1',r));
const close=s=>new Promise(r=>s.close(r));
const sha=x=>createHash('sha256').update(x).digest();
async function fixture(){const dir=await mkdtemp(path.join(os.tmpdir(),'viq-unified-'));let hits=0;const upstream=http.createServer((_q,r)=>{hits++;r.end('{}')});await listen(upstream);const origin='https://phone.test';const gateway=await createPhoneGateway({authDb:path.join(dir,'auth.sqlite'),origin,upstream:`http://127.0.0.1:${upstream.address().port}`,upstreamAuthorization:'test_upstream_authority_0001',testMode:true});await listen(gateway);return{dir,upstream,gateway,origin,base:`http://127.0.0.1:${gateway.address().port}`,get hits(){return hits}}}
async function cleanup(f){await close(f.gateway);await close(f.upstream);await rm(f.dir,{recursive:true,force:true})}
function paired(f,{admin=true,actorId='actor-human'}={}){const seed=f.gateway.authStore.createPair({actorId,admin:true,label:'Issuer'}),{publicKey,privateKey}=generateKeyPairSync('ec',{namedCurve:'P-256'}),jwk=publicKey.export({format:'jwk'}),secret=seed.code.split('.')[1],verifier=sha(Buffer.concat([Buffer.from('viq-phone-pair-verifier-v1\0'),Buffer.from(secret)])),proof=createHmac('sha256',verifier).update(pairRecord(f.origin,seed.intentId,jwk.x,jwk.y)).digest(),device=f.gateway.authStore.consumePair({intent_id:seed.intentId,public_key:{kty:'EC',crv:'P-256',x:jwk.x,y:jwk.y},proof:b64url(proof)});if(!admin)f.gateway.authStore.db.prepare('UPDATE devices SET admin=0 WHERE id=?').run(device.device_id);return{id:device.device_id,privateKey}}
function signed(f,p,target,raw){const c=f.gateway.authStore.challenge({device_id:p.id,method:'POST',target,body_hash:b64url(sha(raw))}),record=proofRecord(f.origin,c.id,Buffer.from(c.nonce,'base64url'),p.id,c.epoch,'POST',target,sha(raw));return{'content-type':'application/json','x-viq-device':p.id,'x-viq-challenge':c.id,'x-viq-signature':b64url(sign(null,record,{key:p.privateKey,dsaEncoding:'ieee-p1363'}))}}

test('signed active admin browser issues exact-schema browser code locally and it pairs a second live browser',async()=>{const f=await fixture();try{const issuer=paired(f),raw=Buffer.from('{"name":"Second browser"}'),response=await fetch(f.base+'/__phone/pairing-codes',{method:'POST',headers:signed(f,issuer,'/__phone/pairing-codes',raw),body:raw});assert.equal(response.status,201);const issued=await response.json();assert.deepEqual(Object.keys(issued).sort(),['code','expires']);assert.equal(f.hits,0);const [intent,secret]=issued.code.split('.'),{publicKey}=generateKeyPairSync('ec',{namedCurve:'P-256'}),jwk=publicKey.export({format:'jwk'}),verifier=sha(Buffer.concat([Buffer.from('viq-phone-pair-verifier-v1\0'),Buffer.from(secret)])),proof=createHmac('sha256',verifier).update(pairRecord(f.origin,intent,jwk.x,jwk.y)).digest();f.gateway.authStore.consumePair({intent_id:intent,public_key:{kty:'EC',crv:'P-256',x:jwk.x,y:jwk.y},proof:b64url(proof)});assert.equal(f.gateway.authStore.db.prepare('SELECT count(*) n FROM devices WHERE active=1 AND actor_id=? AND admin=1').get('actor-human').n,2)}finally{await cleanup(f)}});
test('browser issuance denies unsigned revoked and non-admin, and rejects every extra authority field without intent',async()=>{const f=await fixture();try{const before=()=>f.gateway.authStore.db.prepare('SELECT count(*) n FROM intents').get().n;assert.equal((await fetch(f.base+'/__phone/pairing-codes',{method:'POST',body:'{"name":"x"}'})).status,403);const nonadmin=paired(f,{admin:false}),raw=Buffer.from('{"name":"x"}');assert.equal((await fetch(f.base+'/__phone/pairing-codes',{method:'POST',headers:signed(f,nonadmin,'/__phone/pairing-codes',raw),body:raw})).status,403);const workerRaw=Buffer.from('{"actor_id":"agent","intended_kind":"worker","device_id":"worker-test","device_name":"Worker"}');assert.equal((await fetch(f.base+'/v1/pairing-codes',{method:'POST',headers:signed(f,nonadmin,'/v1/pairing-codes',workerRaw),body:workerRaw})).status,403);assert.equal(f.hits,0);for(const field of ['actor_id','admin','device_id','scope','origin','kind']){const p=paired(f),body=Buffer.from(JSON.stringify({name:'x',[field]:'bad'})),n=before();assert.equal((await fetch(f.base+'/__phone/pairing-codes',{method:'POST',headers:signed(f,p,'/__phone/pairing-codes',body),body})).status,403);assert.equal(before(),n)}const revoked=paired(f);f.gateway.authStore.revoke(revoked.id);const n=before(),body=Buffer.from('{"name":"x"}');assert.equal((await fetch(f.base+'/__phone/pairing-codes',{method:'POST',headers:{'x-viq-device':revoked.id},body})).status,403);assert.equal(before(),n);assert.equal(f.hits,0)}finally{await cleanup(f)}});
