import assert from 'node:assert/strict';
import { mkdtemp, readFile, stat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import test from 'node:test';
import { Store } from '../src/store.js';
import { createApp } from '../src/server.js';
import { defaultCredentialPath, loadCredential, saveCredential } from '../extensions/viq-worker/credential-store.mjs';
import { ViqWorkerRuntime } from '../extensions/viq-worker/worker-runtime.mjs';

async function fixture(now){const dir=await mkdtemp(path.join(tmpdir(),'viq-v3-')),db=path.join(dir,'db.sqlite'),store=new Store(db,{now});await store.init();const coord=await store.bootstrapCoordinator({id:'coord',name:'Coordinator'});await store.createActor({id:'agent-a',name:'Agent A',kind:'agent'});return{dir,db,store,coord}}

test('bound issuance and code-only pairing select exact actor kind id name and reject substitution without consuming',async()=>{const f=await fixture();const issued=await f.store.createPairingCode('coord',{actor_id:'agent-a',intended_kind:'worker',device_id:'tower-a',device_name:'Tower A'});assert.deepEqual({actor:issued.actor_id,kind:issued.intended_kind,id:issued.device_id,name:issued.device_name},{actor:'agent-a',kind:'worker',id:'tower-a',name:'Tower A'});await assert.rejects(f.store.pairDevice({code:issued.code,id:'other',name:'Other'}),e=>e.code==='pairing_device_mismatch');const paired=await f.store.pairDevice({code:issued.code});assert.deepEqual({id:paired.device.id,name:paired.device.name,actor:paired.device.actor_id,kind:paired.device.kind},{id:'tower-a',name:'Tower A',actor:'agent-a',kind:'worker'});await assert.rejects(f.store.pairDevice({code:issued.code}),e=>e.code==='pairing_code_used_or_invalid');await f.store.close()});

test('legacy nullable pairing requires explicit identity',async()=>{const f=await fixture();const issued=await f.store.createPairingCode('coord',{intended_kind:'worker'});await assert.rejects(f.store.pairDevice({code:issued.code}),e=>e.code==='invalid_device');assert.equal((await f.store.pairDevice({code:issued.code,id:'legacy',name:'Legacy'})).device.id,'legacy');await f.store.close()});

test('new admin API requires and UI sends actor kind device id and name',async t=>{const f=await fixture();await f.store.close();const app=await createApp({storage:f.db});await new Promise(r=>app.listen(0,'127.0.0.1',r));t.after(()=>app.close());const post=async body=>{const r=await fetch(`http://127.0.0.1:${app.address().port}/v1/pairing-codes`,{method:'POST',headers:{authorization:`Bearer ${f.coord.credential}`,'content-type':'application/json'},body:JSON.stringify(body)});return{status:r.status,body:await r.json()}};assert.equal((await post({intended_kind:'worker'})).status,400);assert.equal((await post({actor_id:'agent-a',intended_kind:'worker',device_id:'tower-a',device_name:'Tower A'})).status,201);const ui=await readFile(new URL('../web/app.js',import.meta.url),'utf8');for(const field of['actor_id','intended_kind','device_id','device_name'])assert.match(ui,new RegExp(field))});

test('credential JSON is per-home, atomic, private, reusable, and isolated',async()=>{const a=await mkdtemp(path.join(tmpdir(),'viq-home-a-')),b=await mkdtemp(path.join(tmpdir(),'viq-home-b-')),oldHome=process.env.HOME,oldConfig=process.env.XDG_CONFIG_HOME;try{delete process.env.XDG_CONFIG_HOME;process.env.HOME=a;const first=`tower.${'a'.repeat(48)}`;saveCredential(first);assert.equal(loadCredential(),first);assert.equal((await stat(path.dirname(defaultCredentialPath()))).mode&0o777,0o700);assert.equal((await stat(defaultCredentialPath())).mode&0o777,0o600);const second=`tower.${'b'.repeat(48)}`;saveCredential(second);assert.equal(loadCredential(),second);process.env.HOME=b;assert.throws(()=>loadCredential(),/credential/);process.env.HOME=a;assert.equal(loadCredential(),second)}finally{if(oldHome===undefined)delete process.env.HOME;else process.env.HOME=oldHome;if(oldConfig===undefined)delete process.env.XDG_CONFIG_HOME;else process.env.XDG_CONFIG_HOME=oldConfig}});

test('canonical and deprecated names share handler; poll and start use the same session runtime; ordinary root is allowed',async()=>{const source=await readFile(new URL('../extensions/viq-worker/index.ts',import.meta.url),'utf8');assert.match(source,/registerCommand\('viq',command\)/);assert.match(source,/registerCommand\('viq-worker',command\)/);assert.match(source,/o\.sub==='poll'\|\|o\.sub==='start'/);assert.match(source,/lockedDown&&process\.getuid\?\.\(\)===0/);assert.match(source,/VIQ_WORKER_LOCKDOWN/)});

test('package install discovers canonical command in a disposable ordinary Pi profile',async()=>{const home=await mkdtemp(path.join(tmpdir(),'viq-pi-home-')),env={...process.env,HOME:home,PI_OFFLINE:'1'};const installed=spawnSync('pi',['install',process.cwd()],{env,encoding:'utf8'});assert.equal(installed.status,0,installed.stderr);const rpc=spawnSync('pi',['--mode','rpc','--no-session','--offline'],{env,encoding:'utf8',input:'{"type":"get_commands"}\n{"type":"abort"}\n'});assert.equal(rpc.status,0,rpc.stderr);const lines=rpc.stdout.trim().split('\n').map(line=>JSON.parse(line));const commands=lines.find(line=>line.command==='get_commands')?.data?.commands??[];assert.ok(commands.some(command=>command.name==='viq'));assert.ok(commands.some(command=>command.name==='viq-worker'))});

test('credential canary is only an authorization header and never status, body, prompt, argv or environment',async()=>{const canary=`worker.${'CANARY'.repeat(8)}`,seen=[];const runtime=new ViqWorkerRuntime({credential:canary,fetchImpl:async(url,init)=>{seen.push({url,init});return new Response(JSON.stringify({device:{id:'worker',kind:'worker'},actor:{id:'agent'}}),{status:200,headers:{'content-type':'application/json'}})}});await assert.rejects(runtime.start({project:'DOG'}));assert.equal(JSON.stringify(runtime.status()).includes(canary),false);assert.equal(JSON.stringify(seen.map(x=>[x.url,x.init.body])).includes(canary),false);assert.equal(seen[0].init.headers.authorization,`Bearer ${canary}`);assert.equal(process.argv.join(' ').includes(canary),false);assert.equal(JSON.stringify(process.env).includes(canary),false)});
