import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, realpath, symlink } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { Store } from '../src/store.js';
import { createApp } from '../src/server.js';
import { ViqWorkerRuntime } from '../extensions/viq-worker/worker-runtime.mjs';
import { loadCredential, saveCredential } from '../extensions/viq-worker/credential-store.mjs';

async function setup(){const dir=await mkdtemp(path.join(tmpdir(),'viq-worker-pair-')),db=path.join(dir,'db.sqlite');let store=new Store(db);await store.init();const coord=await store.bootstrapCoordinator({id:'coord',name:'Coord'});await store.createActor({id:'worker-a',name:'Worker A',kind:'agent'});await store.close();const app=await createApp({storage:db});await new Promise(r=>app.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${app.address().port}`,req=async(token,method,route,body)=>{const r=await fetch(base+route,{method,headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})},body:body===undefined?undefined:JSON.stringify(body)});const text=await r.text();return{status:r.status,body:text?JSON.parse(text):null}};return{dir,app,base,req,coord}}

test('isolated pairing to assignment to claim to submit tracer excludes device credential from model context and evidence',async t=>{const f=await setup();t.after(()=>f.app.close());const code=await f.req(f.coord.credential,'POST','/v1/pairing-codes',{intended_kind:'worker',actor_id:'worker-a',device_id:'worker-a',device_name:'Worker A'});const prompts=[];const worker=new ViqWorkerRuntime({baseUrl:f.base,pollMs:100000,deliver:async p=>prompts.push(p)});const paired=await worker.pair({code:code.body.code});const secret=paired.credential;assert.equal(JSON.stringify(worker.status()).includes(secret),false);await f.req(f.coord.credential,'POST','/v1/projects',{key:'DOG'});await f.req(f.coord.credential,'POST','/v1/roles',{id:'reviewer',name:'Reviewer'});await f.req(f.coord.credential,'PUT','/v1/devices/coord/roles/reviewer',{});await f.req(f.coord.credential,'POST','/v1/tickets',{project:'DOG',title:'Pair tracer',description:'write receipt',assignment:'Agent'});const status=await worker.start({project:'DOG'});assert.equal(status.ticket,'DOG-1');assert.equal(prompts.length,1);assert.equal(prompts[0].includes(secret),false);assert.equal(prompts[0].includes('claim_token'),false);assert.match(prompts[0],/VIQ TICKET CONTRACT/);assert.match(prompts[0],/\"description\": \"write receipt\"/);await worker.progress('receipt created');await worker.submit({summary:'Receipt created',evidence:['receipt.txt sha256:abc']});const events=(await f.req(f.coord.credential,'GET','/v1/events?ticket=DOG-1')).body.events;assert.deepEqual(events.map(e=>e.type).slice(-4),['claimed','progress','submitted','question_asked']);assert.equal(JSON.stringify(events).includes(secret),false);assert.match(events.find(e=>e.type==='submitted').message,/receipt.txt sha256:abc/);const questions=(await f.req(f.coord.credential,'GET','/v1/tickets/DOG-1/questions')).body.questions;await f.req(f.coord.credential,'POST',`/v1/tickets/DOG-1/questions/${questions[0].id}/answer`,{decision:'accept',note:'ok'});assert.equal((await f.req(f.coord.credential,'GET','/v1/tickets/DOG-1')).body.ticket.state,'Done');assert.equal(JSON.stringify(worker.status()).includes(secret),false)});

test('credential store is external-capable, owner-only, and rejects symlinks',async()=>{const dir=await realpath(await mkdtemp(path.join(tmpdir(),'viq-credential-'))),file=path.join(dir,'state','viq-worker','device-credential'),credential=`worker.${'x'.repeat(48)}`;saveCredential(credential,file);assert.equal(loadCredential(file),credential);const stat=(await import('node:fs/promises')).stat;assert.equal((await stat(file)).mode&0o777,0o600);const link=path.join(dir,'link');await symlink(file,link);assert.throws(()=>loadCredential(link),/unsafe_device_credential_(file|directory)/);const outside=path.join(dir,'outside');await mkdir(outside);const declared=path.join(dir,'declared-state');await symlink(outside,declared);assert.throws(()=>saveCredential(credential,path.join(declared,'viq-worker','device-credential')),/unsafe_device_credential_directory/)});

test('extension allows ordinary root, preserves explicit lockdown, and never embeds credential names in prompts',async()=>{const source=await readFile(new URL('../extensions/viq-worker/index.ts',import.meta.url),'utf8');assert.match(source,/lockedDown&&process\.getuid/);assert.match(source,/registerCommand\('viq'/);const runtime=await readFile(new URL('../extensions/viq-worker/worker-runtime.mjs',import.meta.url),'utf8');assert.doesNotMatch(runtime,/VC_AUTH_TOKEN/);assert.match(runtime,/Never include credentials or secrets/)});


test('readiness and submission are backend-neutral and never invoke publication',async t=>{const f=await setup();t.after(()=>f.app.close());const code=await f.req(f.coord.credential,'POST','/v1/pairing-codes',{intended_kind:'worker',actor_id:'worker-a',device_id:'worker-a',device_name:'Worker A'});let publicationCalls=0;const worker=new ViqWorkerRuntime({baseUrl:f.base,pollMs:100000,syncVault:async()=>{publicationCalls++;throw new Error('publication_must_not_run')}});await worker.pair({code:code.body.code});await f.req(f.coord.credential,'POST','/v1/projects',{key:'DOG'});await f.req(f.coord.credential,'POST','/v1/roles',{id:'reviewer',name:'Reviewer'});await f.req(f.coord.credential,'PUT','/v1/devices/coord/roles/reviewer',{});await f.req(f.coord.credential,'POST','/v1/tickets',{project:'DOG',title:'Neutral edge',assignment:'Agent'});assert.equal((await worker.start({project:'DOG'})).ticket,'DOG-1');await worker.submit({summary:'Implemented neutral edge behavior',evidence:['sha256:abc','https://artifacts.example/report/immutable-1']});assert.equal(publicationCalls,0);const events=(await f.req(f.coord.credential,'GET','/v1/events?ticket=DOG-1')).body.events;assert.match(events.find(e=>e.type==='submitted').message,/Implemented neutral edge behavior/);assert.match(events.find(e=>e.type==='submitted').message,/sha256:abc/)});

test('ambiguous submission retry records one submission under the original fence',async t=>{const f=await setup();t.after(()=>f.app.close());const code=await f.req(f.coord.credential,'POST','/v1/pairing-codes',{intended_kind:'worker',actor_id:'worker-a',device_id:'worker-a',device_name:'Worker A'});const paired=await f.req(null,'POST','/v1/devices/pair',{code:code.body.code});await f.req(f.coord.credential,'POST','/v1/projects',{key:'DOG'});await f.req(f.coord.credential,'POST','/v1/roles',{id:'reviewer',name:'Reviewer'});await f.req(f.coord.credential,'PUT','/v1/devices/coord/roles/reviewer',{});await f.req(f.coord.credential,'POST','/v1/tickets',{project:'DOG',title:'Retry once',assignment:'Agent'});let loseResponse=true;const flaky=async(url,options)=>{const response=await fetch(url,options);if(loseResponse&&new URL(url).pathname.endsWith('/submit')){loseResponse=false;return new Proxy(response,{get(target,key){if(key==='text')return async()=>{throw new Error('response_lost')};const value=Reflect.get(target,key,target);return typeof value==='function'?value.bind(target):value}})}return response};const worker=new ViqWorkerRuntime({baseUrl:f.base,pollMs:100000,credential:paired.body.credential,fetchImpl:flaky});await worker.start({project:'DOG'});const input={summary:'Completed once',evidence:['urn:sha256:abc']};await assert.rejects(worker.submit(input),/response_lost/);assert.equal(worker.status().ticket,'DOG-1');await worker.submit(input);const events=(await f.req(f.coord.credential,'GET','/v1/events?ticket=DOG-1')).body.events;assert.equal(events.filter(e=>e.type==='submitted').length,1);assert.equal(events.filter(e=>e.type==='question_asked').length,1)});

async function continuationFixture(f){const code=await f.req(f.coord.credential,'POST','/v1/pairing-codes',{intended_kind:'worker',actor_id:'worker-a',device_id:'worker-a',device_name:'Worker A'});const paired=await f.req(null,'POST','/v1/devices/pair',{code:code.body.code});await f.req(f.coord.credential,'POST','/v1/projects',{key:'DOG'});await f.req(f.coord.credential,'POST','/v1/roles',{id:'reviewer',name:'Reviewer'});await f.req(f.coord.credential,'PUT','/v1/devices/coord/roles/reviewer',{});for(const title of['Exact resume','Must not claim'])await f.req(f.coord.credential,'POST','/v1/tickets',{project:'DOG',title,assignment:'Agent'});const first=new ViqWorkerRuntime({baseUrl:f.base,pollMs:100000,credential:paired.body.credential});await first.start({project:'DOG'});await first.question('Which constraint?',true);const question=(await f.req(f.coord.credential,'GET','/v1/tickets/DOG-2/questions')).body.questions[0];await f.req(f.coord.credential,'POST',`/v1/tickets/DOG-2/questions/${question.id}/answer`,{answer:'Use the narrow path'});return{paired,question}}

test('answered-question continuation proves exact same actor/device lineage and claims only that ticket',async t=>{const f=await setup();t.after(()=>f.app.close());const{paired}=await continuationFixture(f);const routes=[],prompts=[];const traced=async(url,options)=>{routes.push(`${options?.method??'GET'} ${new URL(url).pathname}`);return fetch(url,options)};const resumed=new ViqWorkerRuntime({baseUrl:f.base,pollMs:100000,credential:paired.body.credential,fetchImpl:traced,deliver:async p=>prompts.push(p)});await resumed.continue('DOG-2');assert.equal(resumed.status().ticket,'DOG-2');assert.equal(routes.includes('POST /v1/tickets/claim-next'),false);assert.equal(routes.includes('POST /v1/tickets/DOG-2/claim'),true);assert.ok(routes.filter(route=>route==='GET /v1/tickets/DOG-2').length>=2);assert.match(prompts[0],/Use the narrow path/);assert.equal((await f.req(f.coord.credential,'GET','/v1/tickets/DOG-1')).body.ticket.claim,null)});

test('continuation rejects an answered question asked by another worker device',async t=>{const f=await setup();t.after(()=>f.app.close());await continuationFixture(f);const code=await f.req(f.coord.credential,'POST','/v1/pairing-codes',{intended_kind:'worker',actor_id:'worker-a',device_id:'worker-b',device_name:'Worker B'}),paired=await f.req(null,'POST','/v1/devices/pair',{code:code.body.code});const worker=new ViqWorkerRuntime({baseUrl:f.base,credential:paired.body.credential});await assert.rejects(worker.continue('DOG-2'),/continuation_provenance_invalid/);assert.equal((await f.req(f.coord.credential,'GET','/v1/tickets/DOG-2')).body.ticket.claim,null)});

test('continuation rejects stale answered-question authority after changes requested',async t=>{const f=await setup();t.after(()=>f.app.close());const{paired}=await continuationFixture(f);const session=await f.req(paired.body.credential,'POST','/v1/sessions',{});const claim=await fetch(`${f.base}/v1/tickets/DOG-2/claim`,{method:'POST',headers:{authorization:`Bearer ${paired.body.credential}`,'x-viq-session-capability':session.body.session_capability,'content-type':'application/json'},body:'{}'}).then(r=>r.json());const authority={claim_id:claim.ticket.claim.claim_id,claim_token:claim.claim_token,generation:claim.ticket.claim.generation};await fetch(`${f.base}/v1/tickets/DOG-2/submit`,{method:'POST',headers:{authorization:`Bearer ${paired.body.credential}`,'x-viq-session-capability':session.body.session_capability,'content-type':'application/json'},body:JSON.stringify({...authority,reviewer:{type:'role',id:'reviewer'},message:'candidate'})});const approval=(await f.req(f.coord.credential,'GET','/v1/tickets/DOG-2/questions')).body.questions.at(-1);await f.req(f.coord.credential,'POST',`/v1/tickets/DOG-2/questions/${approval.id}/answer`,{decision:'request_changes',note:'revise'});const worker=new ViqWorkerRuntime({baseUrl:f.base,credential:paired.body.credential});await assert.rejects(worker.continue('DOG-2'),/continuation_provenance_invalid/);assert.equal((await f.req(f.coord.credential,'GET','/v1/tickets/DOG-2')).body.ticket.claim,null)});
