import assert from 'node:assert/strict';
import { mkdtemp, readFile, realpath, rm, stat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import test from 'node:test';
import { Store } from '../src/store.js';
import { createApp } from '../src/server.js';
import { defaultCredentialPath, loadCredential, saveCredential } from '../extensions/viq-worker/credential-store.mjs';
import { ViqWorkerRuntime } from '../extensions/viq-worker/worker-runtime.mjs';
import { friendlyViqError, parseViqCommand, viqHelp, viqStatus } from '../extensions/viq-worker/command.mjs';

async function fixture(now){const dir=await mkdtemp(path.join(tmpdir(),'viq-v3-')),db=path.join(dir,'db.sqlite'),store=new Store(db,{now});await store.init();const coord=await store.bootstrapCoordinator({id:'coord',name:'Coordinator'});await store.createActor({id:'agent-a',name:'Agent A',kind:'agent'});return{dir,db,store,coord}}

test('bound issuance and code-only pairing select exact actor kind id name and reject substitution without consuming',async()=>{const f=await fixture();const issued=await f.store.createPairingCode('coord',{actor_id:'agent-a',intended_kind:'worker',device_id:'tower-a',device_name:'Tower A'});assert.deepEqual({actor:issued.actor_id,kind:issued.intended_kind,id:issued.device_id,name:issued.device_name},{actor:'agent-a',kind:'worker',id:'tower-a',name:'Tower A'});await assert.rejects(f.store.pairDevice({code:issued.code,id:'other',name:'Other'}),e=>e.code==='pairing_device_mismatch');const paired=await f.store.pairDevice({code:issued.code});assert.deepEqual({id:paired.device.id,name:paired.device.name,actor:paired.device.actor_id,kind:paired.device.kind},{id:'tower-a',name:'Tower A',actor:'agent-a',kind:'worker'});await assert.rejects(f.store.pairDevice({code:issued.code}),e=>e.code==='pairing_code_used_or_invalid');await f.store.close()});

test('legacy nullable pairing requires explicit identity',async()=>{const f=await fixture();const issued=await f.store.createPairingCode('coord',{intended_kind:'worker'});await assert.rejects(f.store.pairDevice({code:issued.code}),e=>e.code==='invalid_device');assert.equal((await f.store.pairDevice({code:issued.code,id:'legacy',name:'Legacy'})).device.id,'legacy');await f.store.close()});

test.skip('VIQ-13+ excluded: Admin device issuance UI fields',{skip:'VIQ-12 paired-board flow is covered by browser-pairing E2E'},async t=>{const f=await fixture();await f.store.close();const app=await createApp({storage:f.db});await new Promise(r=>app.listen(0,'127.0.0.1',r));t.after(()=>app.close());const post=async body=>{const r=await fetch(`http://127.0.0.1:${app.address().port}/v1/pairing-codes`,{method:'POST',headers:{authorization:`Bearer ${f.coord.credential}`,'content-type':'application/json'},body:JSON.stringify(body)});return{status:r.status,body:await r.json()}};assert.equal((await post({intended_kind:'worker'})).status,400);assert.equal((await post({actor_id:'agent-a',intended_kind:'worker',device_id:'tower-a',device_name:'Tower A'})).status,201);const ui=await readFile(new URL('../web/app.js',import.meta.url),'utf8');for(const field of['actor_id','intended_kind','device_id','device_name'])assert.match(ui,new RegExp(field))});

test('credential JSON is per-home, atomic, private, reusable, and isolated',async()=>{const a=await realpath(await mkdtemp(path.join(tmpdir(),'viq-home-a-'))),b=await realpath(await mkdtemp(path.join(tmpdir(),'viq-home-b-'))),oldHome=process.env.HOME,oldConfig=process.env.XDG_CONFIG_HOME;try{delete process.env.XDG_CONFIG_HOME;process.env.HOME=a;const first=`tower.${'a'.repeat(48)}`;saveCredential(first);assert.equal(loadCredential(),first);assert.equal((await stat(path.dirname(defaultCredentialPath()))).mode&0o777,0o700);assert.equal((await stat(defaultCredentialPath())).mode&0o777,0o600);const second=`tower.${'b'.repeat(48)}`;saveCredential(second);assert.equal(loadCredential(),second);process.env.HOME=b;assert.throws(()=>loadCredential(),/credential/);process.env.HOME=a;assert.equal(loadCredential(),second)}finally{if(oldHome===undefined)delete process.env.HOME;else process.env.HOME=oldHome;if(oldConfig===undefined)delete process.env.XDG_CONFIG_HOME;else process.env.XDG_CONFIG_HOME=oldConfig}});

test('relative or empty XDG config roots fail before creating workspace credential paths',async()=>{const workspace=await mkdtemp(path.join(tmpdir(),'viq-relative-xdg-')),oldCwd=process.cwd(),oldConfig=process.env.XDG_CONFIG_HOME;try{process.chdir(workspace);for(const invalid of['relative-config','   ']){process.env.XDG_CONFIG_HOME=invalid;assert.throws(()=>saveCredential(`tower.${'x'.repeat(48)}`),/invalid_config_root/)}await assert.rejects(stat(path.join(workspace,'relative-config')));await assert.rejects(stat(path.join(workspace,'viq')))}finally{process.chdir(oldCwd);if(oldConfig===undefined)delete process.env.XDG_CONFIG_HOME;else process.env.XDG_CONFIG_HOME=oldConfig}});

test('canonical /viq pair pairs and starts the current visible session without a second entrypoint',async()=>{const source=await readFile(new URL('../extensions/viq-worker/index.ts',import.meta.url),'utf8');assert.match(source,/parseViqCommand/);assert.match(source,/await runtime\.pair/);assert.match(source,/await runtime\.start/);assert.match(source,/deliver:async\(prompt:string\)=>\{pi\.sendUserMessage\(prompt,\{deliverAs:'followUp'\}\)\}/);assert.match(source,/registerCommand\('viq',command\)/);assert.doesNotMatch(source,/registerCommand\('viq-worker'/);assert.match(source,/lockedDown&&process\.getuid\?\.\(\)===0/);assert.match(source,/VIQ_WORKER_LOCKDOWN/)});

test('/viq command parsing and human help cover canonical contracts without secrets',()=>{assert.deepEqual(parseViqCommand(''),{sub:'help'});assert.deepEqual(parseViqCommand('pair disposable-code --project DOG'),{sub:'pair',code:'disposable-code',project:'DOG'});assert.deepEqual(parseViqCommand('status'),{sub:'status'});assert.deepEqual(parseViqCommand('poll'),{sub:'poll'});assert.deepEqual(parseViqCommand('continue VIQ-2'),{sub:'continue',ticket:'VIQ-2'});assert.deepEqual(parseViqCommand('stop'),{sub:'stop'});assert.throws(()=>parseViqCommand('mystery'),/Unknown VIQ command.*Run \/viq for help/);const help=viqHelp({paired:false,mode:'stopped'});for(const line of['/viq pair <code>','/viq status','/viq poll','/viq continue <ticket>','/viq stop'])assert.match(help,new RegExp(line.replace(/[<>]/g,'\\$&')));assert.match(help,/Board → Machines/);assert.doesNotMatch(help,/credential|Bearer|disposable-code/)});

test('active clients use canonical local coordinator and exclude the retired default',async()=>{for(const file of['../extensions/viq-worker/index.ts','../extensions/viq-worker/worker-runtime.mjs','../src/http-client.js','../src/phone-gateway.js']){const source=await readFile(new URL(file,import.meta.url),'utf8');assert.doesNotMatch(source,new RegExp(`127\\.0\\.0\\.1:${'73'}${'73'}`));assert.match(source,/127\.0\.0\.1:17373/)}});

test('/viq status and errors explain next steps, target failures, and already-paired state',()=>{const status=viqStatus({paired:true,mode:'stopped',device:'tower',project:null,ticket:null,last_error:null},'https://viq.example');assert.match(status,/paired.*stopped.*Target: https:\/\/viq\.example.*Next: \/viq poll/);assert.doesNotMatch(status,/credential|Bearer/);assert.match(friendlyViqError(new Error('viq_transport_error'),'http://127.0.0.1:17373'),/could not reach.*Check VIQ_URL.*Run \/viq for help/);assert.match(friendlyViqError(new Error('already_paired')),/already paired.*\/viq status/);assert.match(friendlyViqError(new Error('pairing_code_used_or_invalid')),/invalid or already used.*Board → Machines/)});

test('package install discovers canonical command in a disposable ordinary Pi profile',async()=>{const home=await mkdtemp(path.join(process.cwd(),'.viq-pi-home-')),env={...process.env,HOME:home,PI_OFFLINE:'1'},pi=process.env.PI_TEST_CLI??'pi',run=(args,input)=>{const result=spawnSync(pi,args,{env,encoding:'utf8',input});assert.equal(result.error,undefined,`failed to execute ${pi}: ${result.error?.message}`);assert.equal(result.signal,null,`terminated by ${result.signal}: ${result.stderr??''}`);assert.equal(result.status,0,result.stderr);return result};try{run(['install',process.cwd()]);const rpc=run(['--mode','rpc','--no-session','--offline'],'{"type":"get_commands"}\n{"type":"abort"}\n');const lines=rpc.stdout.trim().split('\n').map(line=>JSON.parse(line));const commands=lines.find(line=>line.command==='get_commands')?.data?.commands??[];assert.ok(commands.some(command=>command.name==='viq'));assert.ok(!commands.some(command=>command.name==='viq-worker'))}finally{await rm(home,{recursive:true,force:true})}});

test('credential canary is only an authorization header and never status, body, prompt, argv or environment',async()=>{const canary=`worker.${'CANARY'.repeat(8)}`,seen=[];const runtime=new ViqWorkerRuntime({credential:canary,fetchImpl:async(url,init)=>{seen.push({url,init});const payload=url.endsWith('/v1/sessions')?{session_id:'ps_test',session_capability:'ps_test.secret'}:{device:{id:'worker',kind:'worker'},actor:{id:'agent'}};return new Response(JSON.stringify(payload),{status:url.endsWith('/v1/sessions')?201:200,headers:{'content-type':'application/json'}})}});const started=await runtime.start({project:'DOG'});assert.equal(started.last_error,'invalid_claim_response');assert.equal(JSON.stringify(runtime.status()).includes(canary),false);assert.equal(JSON.stringify(seen.map(x=>[x.url,x.init.body])).includes(canary),false);assert.equal(seen[0].init.headers.authorization,`Bearer ${canary}`);assert.equal(process.argv.join(' ').includes(canary),false);assert.equal(JSON.stringify(process.env).includes(canary),false)});
