import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, symlink } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { Store } from '../src/store.js';
import { createApp } from '../src/server.js';
import { ViqWorkerRuntime } from '../extensions/viq-worker/worker-runtime.mjs';
import { loadCredential, saveCredential } from '../extensions/viq-worker/credential-store.mjs';

async function setup(){const dir=await mkdtemp(path.join(tmpdir(),'viq-worker-pair-')),db=path.join(dir,'db.sqlite');let store=new Store(db);await store.init();const coord=await store.bootstrapCoordinator({id:'coord',name:'Coord'});await store.createActor({id:'worker-a',name:'Worker A',kind:'agent'});await store.close();const app=await createApp({storage:db});await new Promise(r=>app.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${app.address().port}`,req=async(token,method,route,body)=>{const r=await fetch(base+route,{method,headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})},body:body===undefined?undefined:JSON.stringify(body)});const text=await r.text();return{status:r.status,body:text?JSON.parse(text):null}};return{dir,app,base,req,coord}}

test('isolated pairing to assignment to claim to submit tracer excludes device credential from model context and evidence',async t=>{const f=await setup();t.after(()=>f.app.close());const code=await f.req(f.coord.credential,'POST','/v1/pairing-codes',{intended_kind:'worker',actor_id:'worker-a',device_id:'worker-a',device_name:'Worker A'});const prompts=[];const worker=new ViqWorkerRuntime({baseUrl:f.base,pollMs:100000,deliver:async p=>prompts.push(p)});const paired=await worker.pair({code:code.body.code});const secret=paired.credential;assert.equal(JSON.stringify(worker.status()).includes(secret),false);await f.req(f.coord.credential,'POST','/v1/projects',{key:'DOG'});await f.req(f.coord.credential,'POST','/v1/roles',{id:'reviewer',name:'Reviewer'});await f.req(f.coord.credential,'PUT','/v1/devices/coord/roles/reviewer',{});await f.req(f.coord.credential,'POST','/v1/tickets',{project:'DOG',title:'Pair tracer',body:'write receipt',assignee:{type:'device',id:'worker-a'}});const status=await worker.start({project:'DOG'});assert.equal(status.ticket,'DOG-1');assert.equal(prompts.length,1);assert.equal(prompts[0].includes(secret),false);assert.equal(prompts[0].includes('claim_token'),false);await worker.progress('receipt created');await worker.submit('receipt.txt sha256 abc');const events=(await f.req(f.coord.credential,'GET','/v1/events?ticket=DOG-1')).body.events;assert.deepEqual(events.map(e=>e.type).slice(-4),['claimed','progress','submitted','question_asked']);assert.equal(JSON.stringify(events).includes(secret),false);const questions=(await f.req(f.coord.credential,'GET','/v1/tickets/DOG-1/questions')).body.questions;await f.req(f.coord.credential,'POST',`/v1/tickets/DOG-1/questions/${questions[0].id}/answer`,{decision:'accept',note:'ok'});assert.equal((await f.req(f.coord.credential,'GET','/v1/tickets/DOG-1')).body.ticket.state,'done');assert.equal(JSON.stringify(worker.status()).includes(secret),false)});

test('credential store is external-capable, owner-only, and rejects symlinks',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'viq-credential-')),file=path.join(dir,'state','viq-worker','device-credential'),credential=`worker.${'x'.repeat(48)}`;saveCredential(credential,file);assert.equal(loadCredential(file),credential);const stat=(await import('node:fs/promises')).stat;assert.equal((await stat(file)).mode&0o777,0o600);const link=path.join(dir,'link');await symlink(file,link);assert.throws(()=>loadCredential(link),/unsafe_device_credential_(file|directory)/);const outside=path.join(dir,'outside');await mkdir(outside);const declared=path.join(dir,'declared-state');await symlink(outside,declared);assert.throws(()=>saveCredential(credential,path.join(declared,'viq-worker','device-credential')),/unsafe_device_credential_directory/)});

test('extension allows ordinary root, preserves explicit lockdown, and never embeds credential names in prompts',async()=>{const source=await readFile(new URL('../extensions/viq-worker/index.ts',import.meta.url),'utf8');assert.match(source,/lockedDown&&process\.getuid/);assert.match(source,/registerCommand\('viq'/);const runtime=await readFile(new URL('../extensions/viq-worker/worker-runtime.mjs',import.meta.url),'utf8');assert.doesNotMatch(runtime,/VC_AUTH_TOKEN/);assert.match(runtime,/Never include credentials or secrets/)});
