import type { ExtensionAPI, ExtensionCommandContext, ExtensionContext } from '@earendil-works/pi-coding-agent';
import path from 'node:path';
import { lstatSync, realpathSync, statSync } from 'node:fs';
import { ViqWorkerRuntime } from './worker-runtime.mjs';
import { loadCredential, removeCredential, saveCredential } from './credential-store.mjs';
import { loadPoolState, poolState, savePoolState } from './pool-state.mjs';
import { rememberRotationContext, rotateToFreshSession } from './session-rotation.mjs';
import { friendlyViqError, parseViqCommand, viqHelp, viqStatus } from './command.mjs';
const text=(message:string)=>({content:[{type:'text' as const,text:message}],details:{}});
const workerRoot=path.resolve(process.env.VIQ_WORKER_ROOT??'/var/lib/viq-worker/jobs');
const lockedDown=process.env.VIQ_WORKER_LOCKDOWN==='1';
function assertWorkspace(cwd:string){const real=realpathSync(cwd),root=realpathSync(workerRoot),s=statSync(real);if(real===root||!real.startsWith(root+path.sep)||s.uid!==process.getuid()||(s.mode&0o022)!==0)throw new Error('viq-worker requires an owned isolated workspace beneath VIQ_WORKER_ROOT')}
function insideWorkspace(cwd:string,raw:unknown){if(raw==null)return true;if(typeof raw!=='string')return false;const root=realpathSync(cwd),value=raw.replace(/^@/,'');let target=path.resolve(root,value);try{target=realpathSync(target)}catch{try{const parent=realpathSync(path.dirname(target));target=path.join(parent,path.basename(target));if(lstatSync(parent).isSymbolicLink())return false}catch{return false}}return target===root||target.startsWith(root+path.sep)}
export default function(pi:ExtensionAPI){
 let ctxRef:ExtensionContext|undefined,continuationTimer:ReturnType<typeof setInterval>|undefined,rotationPending=false;let initialCredential:string|null=null;try{initialCredential=loadCredential()}catch{}
 const baseUrl=process.env.VIQ_URL??'http://127.0.0.1:17373';
 const runtime=new ViqWorkerRuntime({baseUrl,pollMs:Number(process.env.VIQ_WORKER_POLL_MS??3000),credential:initialCredential,onCredentialInvalidated:async()=>{removeCredential();savePoolState(poolState(null,false));initialCredential=null},deliver:async(prompt:string)=>{pi.sendUserMessage(prompt,{deliverAs:'followUp'})},onStatus:(s:any)=>ctxRef?.ui.setStatus('viq',`viq ${s.mode}${s.ticket?` · ${s.ticket}`:''}${s.last_error?` · ${s.last_error}`:''}`)});
 const clearContinuation=()=>{if(continuationTimer){clearInterval(continuationTimer);continuationTimer=undefined}};
 const boot=async(ctx:ExtensionContext)=>{const state=loadPoolState();if(!state?.enabled)return;if(lockedDown)assertWorkspace(ctx.cwd);if(state.continue_ticket){const attempt=async()=>{if(runtime.status().mode!=='stopped')return;try{await runtime.continue(state.continue_ticket);clearContinuation()}catch(error){const code=error instanceof Error?error.message:String(error);if(!['ticket_not_eligible_for_continuation','continuation_provenance_invalid'].includes(code)){clearContinuation();ctx.ui.notify(friendlyViqError(error,baseUrl),'error')}}};continuationTimer=setInterval(attempt,Number(process.env.VIQ_WORKER_POLL_MS??3000));continuationTimer.unref?.();await attempt()}else await runtime.start()};
 const rotate=(ticket:string|null)=>{savePoolState(poolState(ticket));rotationPending=true};
 pi.on('session_start',(_event,ctx)=>{ctxRef=ctx;void boot(ctx).catch(error=>ctx.ui.notify(friendlyViqError(error,baseUrl),'error'))});pi.on('session_shutdown',async()=>{clearContinuation();await runtime.shutdown();ctxRef=undefined});
 pi.on('agent_settled',(_event,ctx)=>{if(!rotationPending)return;rotationPending=false;setTimeout(()=>void rotateToFreshSession().catch(error=>ctx.ui.notify(friendlyViqError(error,baseUrl),'error')),0)});
 pi.on('tool_call',(event,ctx)=>{if(!lockedDown)return;if(event.toolName==='bash')return{block:true,reason:'shell access is disabled in VIQ_WORKER_LOCKDOWN'};if(['read','write','edit','grep','find','ls'].includes(event.toolName)){const raw=(event.input as any)?.path;if(!insideWorkspace(path.resolve(ctx.cwd),raw))return{block:true,reason:'viq-worker tools are confined to the isolated ticket workspace'}}});
 pi.on('user_bash',()=>!lockedDown?undefined:{result:{output:'shell access is disabled in VIQ_WORKER_LOCKDOWN',exitCode:126,cancelled:false,truncated:false}});
 const command={description:'Pair and run VIQ in this visible Pi session',handler:async(raw:string,ctx:ExtensionCommandContext)=>{ctxRef=ctx;rememberRotationContext(ctx);try{const o=parseViqCommand(raw);if(o.sub==='help'){ctx.ui.notify(viqHelp(runtime.status()),'info');return}if(lockedDown&&process.getuid?.()===0)throw new Error('VIQ_WORKER_LOCKDOWN refuses root');if(o.sub==='pair'){if(!o.code)throw new Error('Usage: /viq pair <code>');const result=await runtime.pair({code:o.code,...(o.id?{id:o.id}:{}),...(o.name?{name:o.name}:{})});try{saveCredential(result.credential)}catch(error){runtime.setCredential(initialCredential);throw error}if(lockedDown)assertWorkspace(ctx.cwd);savePoolState(poolState(null,false));ctx.ui.notify(`Paired VIQ machine ${result.device.id} · stopped · endpoint ${baseUrl}. Next: /viq poll or /viq once`,'info')}else if(o.sub==='unpair'){await runtime.unpair();removeCredential();savePoolState(poolState(null,false));initialCredential=null;ctx.ui.notify(`Unpaired this Pi locally · stopped · endpoint ${baseUrl}. The coordinator device record remains for human revoke/audit.`,'info')}else if(o.sub==='poll'||o.sub==='start'){if(lockedDown)assertWorkspace(ctx.cwd);savePoolState(poolState());const s=await runtime.start(o.project?{project:o.project}:{});ctx.ui.notify(`VIQ worker ${s.device??'unknown'} · persistent ${s.mode} · ticket ${s.ticket??'none'} · endpoint ${baseUrl}. ${s.ticket?'Claim verified; work may begin.':'No work; idle backoff active.'} Next: /viq status`,'info')}else if(o.sub==='once'){if(lockedDown)assertWorkspace(ctx.cwd);savePoolState(poolState(null,false));const s=o.ticket?await runtime.claim(o.ticket):await runtime.start({once:true});ctx.ui.notify(`VIQ worker ${s.device??'unknown'} · once ${s.mode} · ticket ${s.ticket??'none'} · endpoint ${baseUrl}. ${s.ticket?'Claim verified; work may begin.':'No eligible work; one-shot complete.'}`,'info')}else if(o.sub==='claim'){if(lockedDown)assertWorkspace(ctx.cwd);const s=await runtime.claim(o.ticket);ctx.ui.notify(`Claimed exact eligible ticket ${s.ticket}. Next: /viq status`,'info')}else if(o.sub==='continue'){if(lockedDown)assertWorkspace(ctx.cwd);const s=await runtime.continue(o.ticket);ctx.ui.notify(`Continued exact ticket ${s.ticket} with its answered history. Next: /viq status`,'info')}else if(o.sub==='status'){ctx.ui.notify(viqStatus(runtime.status(),baseUrl),'info')}else if(o.sub==='pause'){runtime.pause();ctx.ui.notify('VIQ polling paused. Run /viq resume to continue.','info')}else if(o.sub==='resume'){runtime.resume();ctx.ui.notify('VIQ polling resumed. Run /viq status to inspect it.','info')}else if(o.sub==='stop'){savePoolState(poolState(null,false));await runtime.stop();ctx.ui.notify('VIQ polling stopped. Run /viq poll to start again.','info')}}catch(error){throw new Error(friendlyViqError(error,baseUrl))}}};
 pi.registerCommand('viq',command);
 const message={type:'object',properties:{message:{type:'string',minLength:1,maxLength:8000}},required:['message'],additionalProperties:false} as const;
 const uri={type:'string',minLength:1,maxLength:2000} as const;
 const submission={type:'object',properties:{version:{type:'number',const:1},summary:{type:'string',minLength:1,maxLength:8000},evidence:{type:'array',minItems:1,maxItems:100,items:{type:'object',properties:{kind:{type:'string',enum:['preview','pr','commit','screenshot','test','log','build','asset','other']},label:{type:'string',minLength:1,maxLength:200},uri,digest:{type:'string',maxLength:200}},required:['kind','label','uri'],additionalProperties:false}},verification_steps:{type:'array',minItems:1,maxItems:100,items:{type:'string',minLength:1,maxLength:2000}},tests:{type:'array',minItems:1,maxItems:100,items:{type:'object',properties:{name:{type:'string',minLength:1,maxLength:200},status:{type:'string',enum:['passed','failed','not-run']},uri},required:['name','status'],additionalProperties:false}},caveats:{type:'array',maxItems:100,items:{type:'string',minLength:1,maxLength:2000}},ui_change:{type:'boolean'},preview_url:uri,screenshots:{type:'array',maxItems:100,items:{type:'object',properties:{label:{type:'string',minLength:1,maxLength:200},uri,digest:{type:'string',maxLength:200}},required:['label','uri'],additionalProperties:false}},source:{type:'object',properties:{commit:{type:'string',maxLength:200},pr:uri},additionalProperties:false},release:{type:'object',properties:{status:{type:'string',enum:['not-released','released','production-verified']},build_id:{type:'string',maxLength:200},reference:uri},required:['status'],additionalProperties:false}},required:['version','summary','evidence','verification_steps','tests','caveats','ui_change','screenshots','source','release'],additionalProperties:false} as const;
 const question={type:'object',properties:{message:{type:'string',minLength:1,maxLength:8000},blocking:{type:'boolean',description:'True releases the claim and moves the ticket to Waiting; false leaves Working unchanged.'}},required:['message','blocking'],additionalProperties:false} as const;
 pi.registerTool({name:'viq_progress',label:'VIQ progress',description:'Record non-secret progress for the currently claimed VIQ ticket.',parameters:message,async execute(_id,p){return text(`Progress recorded for ${(await runtime.progress(p.message)).ticket}`)}});
 pi.registerTool({name:'viq_question',label:'VIQ question',description:'Ask the reviewer a question for the currently claimed VIQ ticket.',parameters:question,async execute(_id,p){const result=await runtime.question(p.message,p.blocking);if(result.blocking)rotate(null);return{...text(`${result.blocking?'Blocking':'Non-blocking'} question recorded for ${result.ticket}${result.blocking?'; claim released and persistent lane will rotate to other eligible work':''}`),...(result.blocking?{terminate:true}:{})}}});
 pi.registerTool({name:'viq_block',label:'VIQ block',description:'Record a blocker and pause while retaining the current claim.',parameters:message,async execute(_id,p){return{...text(`Blocked ${(await runtime.block(p.message)).ticket}`),terminate:true}}});
 pi.registerTool({name:'viq_submit',label:'VIQ submit',description:'Submit a backend-neutral Review Bundle: summary, evidence assets/links, verification steps, tests, caveats, optional preview/screenshots/source, and factual release status. This records references only and never publishes or deploys.',parameters:submission,async execute(_id,p){const result=await runtime.submit(p);if(runtime.status().lane_mode==='persistent')rotate(null);else savePoolState(poolState(null,false));return{...text(`Submitted ${result.ticket} for Human Review; accepted is not deployed${runtime.status().lane_mode==='persistent'?'; rotating to a fresh pool session':''}`),terminate:true}}});
 pi.registerTool({name:'viq_release',label:'VIQ release',description:'Release the currently claimed ticket with a reason.',parameters:message,async execute(_id,p){const result=await runtime.release(p.message);if(runtime.status().lane_mode==='persistent')rotate(null);else savePoolState(poolState(null,false));return{...text(`Released ${result.ticket}${runtime.status().lane_mode==='persistent'?'; rotating to a fresh pool session':''}`),terminate:true}}})
}
