import type { ExtensionAPI, ExtensionContext } from '@earendil-works/pi-coding-agent';
import path from 'node:path';
import { lstatSync, realpathSync, statSync } from 'node:fs';
import { ViqWorkerRuntime } from './worker-runtime.mjs';
import { loadCredential, saveCredential } from './credential-store.mjs';
import { runVaultSync } from './vault-sync.mjs';
import { friendlyViqError, parseViqCommand, viqHelp, viqStatus } from './command.mjs';
const text=(message:string)=>({content:[{type:'text' as const,text:message}],details:{}});
const workerRoot=path.resolve(process.env.VIQ_WORKER_ROOT??'/var/lib/viq-worker/jobs');
const lockedDown=process.env.VIQ_WORKER_LOCKDOWN==='1';
function assertWorkspace(cwd:string){const real=realpathSync(cwd),root=realpathSync(workerRoot),s=statSync(real);if(real===root||!real.startsWith(root+path.sep)||s.uid!==process.getuid()||(s.mode&0o022)!==0)throw new Error('viq-worker requires an owned isolated workspace beneath VIQ_WORKER_ROOT')}
function insideWorkspace(cwd:string,raw:unknown){if(raw==null)return true;if(typeof raw!=='string')return false;const root=realpathSync(cwd),value=raw.replace(/^@/,'');let target=path.resolve(root,value);try{target=realpathSync(target)}catch{try{const parent=realpathSync(path.dirname(target));target=path.join(parent,path.basename(target));if(lstatSync(parent).isSymbolicLink())return false}catch{return false}}return target===root||target.startsWith(root+path.sep)}
export default function(pi:ExtensionAPI){
 let ctxRef:ExtensionContext|undefined;let initialCredential:string|null=null;try{initialCredential=loadCredential()}catch{}
 const visible=(message:string)=>ctxRef?.ui.notify(message,'info');
 const baseUrl=process.env.VIQ_URL??'http://127.0.0.1:7373';
 const runtime=new ViqWorkerRuntime({baseUrl,pollMs:Number(process.env.VIQ_WORKER_POLL_MS??3000),credential:initialCredential,deliver:async(prompt:string)=>{pi.sendUserMessage(prompt,{deliverAs:'followUp'})},syncVault:async input=>{if(!ctxRef)throw new Error('pi_session_not_ready');visible(`vault-sync ${input.phase} started`);const result=await runVaultSync({cwd:path.resolve(ctxRef.cwd),onOutput:line=>visible(`vault-sync: ${line.slice(0,300)}`)});visible(`vault-sync ${input.phase} published ${result.commit}`);return result},onStatus:(s:any)=>ctxRef?.ui.setStatus('viq',`viq ${s.mode}${s.ticket?` · ${s.ticket}`:''}${s.last_error?` · ${s.last_error}`:''}`)});
 pi.on('session_start',(_event,ctx)=>{ctxRef=ctx});pi.on('session_shutdown',async()=>{await runtime.shutdown();ctxRef=undefined});
 pi.on('tool_call',(event,ctx)=>{if(!lockedDown)return;if(event.toolName==='bash')return{block:true,reason:'shell access is disabled in VIQ_WORKER_LOCKDOWN'};if(['read','write','edit','grep','find','ls'].includes(event.toolName)){const raw=(event.input as any)?.path;if(!insideWorkspace(path.resolve(ctx.cwd),raw))return{block:true,reason:'viq-worker tools are confined to the isolated ticket workspace'}}});
 pi.on('user_bash',()=>!lockedDown?undefined:{result:{output:'shell access is disabled in VIQ_WORKER_LOCKDOWN',exitCode:126,cancelled:false,truncated:false}});
 const command={description:'Pair and run VIQ in this visible Pi session',handler:async(raw:string,ctx:ExtensionContext)=>{ctxRef=ctx;try{const o=parseViqCommand(raw);if(o.sub==='help'){ctx.ui.notify(viqHelp(runtime.status()),'info');return}if(lockedDown&&process.getuid?.()===0)throw new Error('VIQ_WORKER_LOCKDOWN refuses root');if(o.sub==='pair'){if(!o.code)throw new Error('Usage: /viq pair <code>');if(runtime.status().paired)throw new Error('already_paired');const result=await runtime.pair({code:o.code,...(o.id?{id:o.id}:{}),...(o.name?{name:o.name}:{})});try{saveCredential(result.credential)}catch(error){runtime.setCredential(initialCredential);throw error}if(lockedDown)assertWorkspace(ctx.cwd);const s=await runtime.start({project:o.project??process.env.VIQ_PROJECT??'VIQ'});ctx.ui.notify(`Paired VIQ machine ${result.device.id}; worker is ${s.mode}. Next: /viq status`,'info')}else if(o.sub==='poll'||o.sub==='start'){if(lockedDown)assertWorkspace(ctx.cwd);const s=await runtime.start({project:o.project??process.env.VIQ_PROJECT??'VIQ'});ctx.ui.notify(`VIQ worker is ${s.mode} for ${s.project}. Next: /viq status`,'info')}else if(o.sub==='status'){ctx.ui.notify(viqStatus(runtime.status(),baseUrl),'info')}else if(o.sub==='pause'){runtime.pause();ctx.ui.notify('VIQ polling paused. Run /viq resume to continue.','info')}else if(o.sub==='resume'){runtime.resume();ctx.ui.notify('VIQ polling resumed. Run /viq status to inspect it.','info')}else if(o.sub==='stop'){await runtime.stop();ctx.ui.notify('VIQ polling stopped. Run /viq poll to start again.','info')}}catch(error){throw new Error(friendlyViqError(error,baseUrl))}}};
 pi.registerCommand('viq',command);
 const message={type:'object',properties:{message:{type:'string',minLength:1,maxLength:8000}},required:['message'],additionalProperties:false} as const;
 const question={type:'object',properties:{message:{type:'string',minLength:1,maxLength:8000},blocking:{type:'boolean',description:'True releases the claim and moves the ticket to Waiting; false leaves Working unchanged.'}},required:['message','blocking'],additionalProperties:false} as const;
 pi.registerTool({name:'viq_progress',label:'VIQ progress',description:'Record non-secret progress for the currently claimed VIQ ticket.',parameters:message,async execute(_id,p){return text(`Progress recorded for ${(await runtime.progress(p.message)).ticket}`)}});
 pi.registerTool({name:'viq_question',label:'VIQ question',description:'Ask the reviewer a question for the currently claimed VIQ ticket.',parameters:question,async execute(_id,p){const result=await runtime.question(p.message,p.blocking);return{...text(`${result.blocking?'Blocking':'Non-blocking'} question recorded for ${result.ticket}${result.blocking?'; start a fresh Pi session before resuming':''}`),...(result.blocking?{terminate:true}:{})}}});
 pi.registerTool({name:'viq_block',label:'VIQ block',description:'Record a blocker and pause while retaining the current claim.',parameters:message,async execute(_id,p){return{...text(`Blocked ${(await runtime.block(p.message)).ticket}`),terminate:true}}});
 pi.registerTool({name:'viq_submit',label:'VIQ submit',description:'Publish the Vault, then submit the claimed ticket with canonical commit evidence.',parameters:message,async execute(_id,p){const result=await runtime.submit(p.message);return{...text(`Published ${result.commit} and submitted ${result.ticket}; start a fresh Pi session before resuming`),terminate:true}}});
 pi.registerTool({name:'viq_release',label:'VIQ release',description:'Release the currently claimed ticket with a reason.',parameters:message,async execute(_id,p){return{...text(`Released ${(await runtime.release(p.message)).ticket}; start a fresh Pi session before resuming`),terminate:true}}})
}
