import type { ExtensionAPI, ExtensionCommandContext, ExtensionContext } from '@earendil-works/pi-coding-agent';
import { ViqWorkerRuntime } from './worker-runtime.mjs';
import { credentialPath, loadCredential, removeCredential, saveCredential } from './credential-store.mjs';
import { friendlyViqError, parseViqCommand, viqHelp, viqStatus } from './command.mjs';
import { attach, captureTransition, clearTransition, controller, current, detach } from './controller.mjs';
type TransitionContext=Pick<ExtensionCommandContext,'newSession'>;
const text=(value:string)=>({content:[{type:'text' as const,text:value}],details:{}});
const replacement=async(ctx:TransitionContext)=>captureTransition(ctx);
const episodeEntry='viq-worker-ticket-episode';
const markEpisode=(api:ExtensionAPI,ticketId:string)=>api.appendEntry(episodeEntry,{version:1,ticket_id:ticketId});
const episodeUsed=(ctx:ExtensionContext)=>ctx.sessionManager.getEntries().some(entry=>entry.type==='custom'&&entry.customType===episodeEntry);
const episodeText=(episode:any)=>['This canonical VIQ ticket contract and history are the sole task context. Never expose credentials or secrets.','','VIQ TICKET CONTRACT',JSON.stringify(episode.ticket,null,2),'','VIQ HISTORY',JSON.stringify(episode.history,null,2)].join('\n');
export default function(pi:ExtensionAPI){
 let credential:string|null=null,selectedCredentialFile:string|null=null;try{selectedCredentialFile=credentialPath();credential=loadCredential(selectedCredentialFile)}catch{}
 const baseUrl=process.env.VIQ_URL??'http://127.0.0.1:17373';
 if(!controller.runtime)controller.runtime=new ViqWorkerRuntime({baseUrl,pollMs:Number(process.env.VIQ_WORKER_POLL_MS??3000),credential,credentialFile:selectedCredentialFile,deliver:async(prompt:string,ticket:any)=>{const a=controller.adapter;if(!a)throw new Error('viq_session_unavailable');if(ticket?.id){markEpisode(a.pi,ticket.id);a.pi.setSessionName(`VIQ ${ticket.id}${ticket.title?` · ${ticket.title}`:''}`)}a.pi.sendUserMessage(prompt,{deliverAs:'followUp'})},onCredentialInvalidated:async(file:string|null)=>removeCredential(file??undefined),onStatus:(s:any)=>controller.adapter?.ctx.ui.setStatus('viq',`viq ${s.mode}${s.ticket?` · ${s.ticket}`:''}`)});
 const runtime=controller.runtime;let taking=false;
 const startPending=async(epoch:number)=>{if(!controller.pendingStart||!current(epoch)||runtime.status().mode!=='stopped')return;const ticket=controller.pendingTicket,credentialFile=controller.pendingCredentialFile;controller.pendingStart=false;controller.pendingTicket=null;controller.pendingCredentialFile=null;await runtime.start(ticket?{ticket,...(credentialFile?{credentialFile}:{})}:{})};
 const cancelled=(epoch:number)=>{controller.pendingStart=false;controller.pendingTicket=null;controller.pendingCredentialFile=null;controller.persistent=false;clearTransition(epoch);runtime.rotationCancelled();current(epoch)?.ctx.ui.notify(friendlyViqError(new Error('viq_rotation_cancelled'),baseUrl),'error')};
 pi.on('session_start',(_event,ctx)=>{const epoch=attach({pi,ctx});void startPending(epoch).catch(error=>current(epoch)?.ctx.ui.notify(friendlyViqError(error,baseUrl),'error'))});
 pi.on('session_shutdown',async()=>{const epoch=controller.adapter?.epoch;if(epoch)detach(epoch);if(!controller.adapter)await runtime.shutdown()});
 pi.on('agent_settled',(_event,_ctx)=>{const epoch=controller.adapter?.epoch;void(async()=>{if(!epoch||!current(epoch))return;const state=await runtime.settled();if(state.retired||!current(epoch)||state.active||!controller.persistent||runtime.status().mode!=='stopped'||!runtime.status().rotation_required||controller.rotating)return;const transition=current(epoch)?.transition;if(!transition)return;controller.rotating=true;controller.pendingStart=true;try{const result=await transition.newSession({withSession:replacement});if(result.cancelled)cancelled(epoch)}catch(error){controller.pendingStart=false;current(epoch)?.ctx.ui.notify(friendlyViqError(error,baseUrl),'error')}finally{controller.rotating=false}})().catch(error=>current(epoch??-1)?.ctx.ui.notify(friendlyViqError(error,baseUrl),'error'))});
 pi.registerCommand('viq',{description:'Pair and run Viq in this visible Pi session',handler:async(raw:string,ctx:ExtensionCommandContext)=>{const epoch=controller.adapter?.epoch;const o=parseViqCommand(raw);if(o.sub==='help'){ctx.ui.notify(viqHelp(runtime.status()),'info');return}try{if(o.sub==='pair'){const paired=await runtime.pair({code:o.code});saveCredential(paired.credential,runtime.credentialFile??undefined);ctx.ui.notify(`Paired ${paired.device.id}. Next: /viq poll or /viq take PROJECT-N.`,'info');return}if(o.sub==='unpair'){await runtime.unpair();removeCredential(runtime.credentialFile??undefined);ctx.ui.notify('Unpaired this Pi locally.','info');return}if(o.sub==='status'){ctx.ui.notify(viqStatus(runtime.status(),baseUrl),'info');return}if(o.sub==='stop'){controller.persistent=false;controller.pendingTicket=null;controller.pendingCredentialFile=null;await runtime.stop();ctx.ui.notify('Viq poll stopped.','info');return}if(o.sub==='poll'){if(runtime.status().mode!=='stopped'||controller.rotating)throw new Error('worker_already_started');controller.persistent=true;controller.pendingTicket=null;controller.pendingCredentialFile=null;runtime.project=o.project??null;controller.pendingStart=true;controller.rotating=true;try{const result=await ctx.newSession({withSession:replacement});if(result.cancelled)cancelled(epoch??-1)}finally{controller.rotating=false}return}if(o.sub==='take'){if(runtime.status().mode!=='stopped'||controller.rotating)throw new Error('worker_already_started');controller.persistent=false;controller.pendingTicket=o.ticket;controller.pendingCredentialFile=o.credentialFile??null;controller.pendingStart=true;controller.rotating=true;try{const result=await ctx.newSession({withSession:replacement});if(result.cancelled)cancelled(epoch??-1)}finally{controller.rotating=false}return}if(o.sub==='once'){if(episodeUsed(ctx))throw new Error('viq_episode_reuse_forbidden');if(runtime.status().mode!=='stopped')throw new Error('worker_already_started');controller.persistent=false;controller.pendingTicket=null;controller.pendingCredentialFile=null;await runtime.start({once:true});return}}catch(error){if(current(epoch??-1))throw new Error(friendlyViqError(error,baseUrl))}}});
 const take={type:'object',properties:{ticket_id:{type:'string',pattern:'^[A-Z][A-Z0-9]{1,9}-[1-9][0-9]*$',maxLength:40},credential_file:{type:'string',pattern:'^/',maxLength:4096}},required:['ticket_id'],additionalProperties:false} as const;
 const message={type:'object',properties:{message:{type:'string',minLength:1,maxLength:8000}},required:['message'],additionalProperties:false} as const;
 const question={type:'object',properties:{message:{type:'string',minLength:1,maxLength:8000},blocking:{type:'boolean'}},required:['message','blocking'],additionalProperties:false} as const;
 const completion={type:'object',properties:{outcome:{type:'string',minLength:1,maxLength:1000},evidence:{type:'array',maxItems:50,items:{type:'string',minLength:1,maxLength:2000}}},required:['outcome'],additionalProperties:false} as const;
 const submission={type:'object',properties:{version:{type:'number',const:1},summary:{type:'string',minLength:1},evidence:{type:'array',minItems:1,items:{type:'object'}},verification_steps:{type:'array',minItems:1,items:{type:'string'}},tests:{type:'array',minItems:1,items:{type:'object'}},caveats:{type:'array',items:{type:'string'}},ui_change:{type:'boolean'},screenshots:{type:'array',items:{type:'object'}},source:{type:'object'},release:{type:'object'}},required:['version','summary','evidence','verification_steps','tests','caveats','ui_change','screenshots','source','release'],additionalProperties:false} as const;
 pi.registerTool({name:'viq_take',label:'VIQ take',description:'In an externally-created fresh Pi episode, claim exactly ticket_id through the public Viq claim path. An optional absolute credential_file selects an owner-only paired credential; tokens are never accepted. Returns only canonical non-secret ticket/history and denies active or terminal episode reuse.',parameters:take,async execute(_id,p,_signal,_onUpdate,ctx){if(taking||runtime.status().mode!=='stopped'||episodeUsed(ctx))throw new Error('viq_episode_reuse_forbidden');taking=true;try{const result=await runtime.start({ticket:p.ticket_id,...(p.credential_file?{credentialFile:p.credential_file}:{}),deliver:false});if(!result.episode)throw new Error('ticket_not_claimed');markEpisode(pi,result.episode.ticket.id);pi.setSessionName(`VIQ ${result.episode.ticket.id}${result.episode.ticket.title?` · ${result.episode.ticket.title}`:''}`);return{content:[{type:'text' as const,text:episodeText(result.episode)}],details:{ticket_id:result.episode.ticket.id}}}finally{taking=false}}});
 pi.registerTool({name:'viq_progress',label:'VIQ progress',description:'Record non-secret progress.',parameters:message,async execute(_id,p){return text(`Progress recorded for ${(await runtime.progress(p.message)).ticket}`)}});
 pi.registerTool({name:'viq_question',label:'VIQ question',description:'Ask a reviewer question.',parameters:question,async execute(_id,p){const r=await runtime.question(p.message,p.blocking);return{...text(`Question recorded for ${r.ticket}`),...(r.blocking?{terminate:true}:{})}}});
 pi.registerTool({name:'viq_block',label:'VIQ block',description:'Record a blocker.',parameters:message,async execute(_id,p){return{...text(`Blocked ${(await runtime.block(p.message)).ticket}`),terminate:true}}});
 pi.registerTool({name:'viq_complete',label:'VIQ complete',description:'Directly complete the current fenced ticket with a concise outcome and optional immutable opaque evidence references. Never include credentials or secrets.',parameters:completion,async execute(_id,p){return{...text(`Completed ${(await runtime.complete({outcome:p.outcome,evidence:p.evidence??[]})).ticket}`),terminate:true}}});
 pi.registerTool({name:'viq_submit',label:'VIQ submit',description:'Record a review bundle.',parameters:submission,async execute(_id,p){return{...text(`Submitted ${(await runtime.submit(p)).ticket}`),terminate:true}}});
 pi.registerTool({name:'viq_release',label:'VIQ release',description:'Release the current ticket.',parameters:message,async execute(_id,p){return{...text(`Released ${(await runtime.release(p.message)).ticket}`),terminate:true}}});
}
