import { legacyReviewBundle, normalizeReviewBundle } from './review-bundle.mjs';
const clean=(v,n,max=8000)=>{if(typeof v!=='string'||!v.trim()||v.length>max)throw new Error(`invalid_${n}`);return v.trim()};
const httpError=(status,code)=>Object.assign(new Error(code),{status,code,classification:'http'});
const credentialError=e=>e?.classification==='http'&&e.status===401&&['device_revoked','actor_inactive','device_unauthorized'].includes(e.code);
const publicHistory=events=>(events??[]).map(({cursor,type,actor,message,metadata,created_at})=>({cursor,type,actor,message,metadata,created_at}));
export class ViqWorkerRuntime {
 constructor({baseUrl='http://127.0.0.1:17373',pollMs=3000,heartbeatMs=30000,deliver=async()=>{},onStatus=()=>{},onCredentialInvalidated=async()=>{},fetchImpl=fetch,credential=null}={}){Object.assign(this,{baseUrl:baseUrl.replace(/\/$/,''),pollMs,heartbeatMs,deliver,onStatus,onCredentialInvalidated,fetch:fetchImpl,credential,mode:'stopped',laneMode:'stopped',device:null,actor:null,project:null,current:null,session:null,busy:false,timer:null,heartbeatTimer:null,abort:null,noWork:0,nextPollAt:0,lastError:null,rotationRequired:false,requestSerial:0});}
 status(){return{mode:this.mode,lane_mode:this.laneMode,device:this.device,project:this.project,ticket:this.current?.ticket.id??null,paired:Boolean(this.credential),last_error:this.lastError,rotation_required:this.rotationRequired,next_retry_ms:this.mode==='waiting'?Math.max(0,this.nextPollAt-Date.now()):0};}
 rotationCancelled(){this.mode='stopped';this.laneMode='stopped';this.rotationRequired=false;this.lastError='viq_rotation_cancelled';this.#notify();return this.status()}
 #notify(){this.onStatus(this.status())} #fail(e){this.lastError=e instanceof Error?e.message:String(e);this.#notify()}
 setCredential(value){if(value!==null&&(typeof value!=='string'||value.length<32))throw new Error('invalid_device_credential');this.credential=value}
 async #request(method,route,body,{session=true,signal,authenticated=true}={}){if(authenticated&&!this.credential)throw new Error('device_not_paired');let r;try{r=await this.fetch(this.baseUrl+route,{method,headers:{'content-type':'application/json',...(authenticated?{authorization:`Bearer ${this.credential}`}:{}),...(session&&this.session?.capability?{'x-viq-session-capability':this.session.capability}:{})},body:body===undefined?undefined:JSON.stringify(body),signal})}catch(e){if(e?.name==='AbortError')throw new Error('viq_wait_cancelled');throw new Error('viq_transport_error')}let value=null;const raw=await r.text();try{value=raw?JSON.parse(raw):null}catch{throw new Error('viq_invalid_response')}if(!r.ok){const e=httpError(r.status,value?.error?.code??`viq_http_${r.status}`);if(credentialError(e)){this.credential=null;await this.onCredentialInvalidated()}throw e}return{status:r.status,value}}
 async #identify(){const r=await this.#request('GET','/v1/devices/me',undefined,{session:false});if(r.value?.device?.kind!=='worker')throw new Error('paired_device_is_not_worker');this.device=r.value.device.id;this.actor=r.value.actor?.id}
 async #open(){const r=await this.#request('POST','/v1/sessions',{});if(typeof r.value?.session_id!=='string'||typeof r.value?.session_capability!=='string')throw new Error('invalid_session_response');this.session={id:r.value.session_id,capability:r.value.session_capability}}
 async #close(){if(!this.session)return;await this.#request('POST','/v1/sessions/close',{});this.session=null}
 #authority(){if(!this.current||!this.session)throw new Error('no_claimed_ticket');return{claim_id:this.current.claim_id,generation:this.current.generation,claim_token:this.current.claim_token}}
 #requestId(kind){return `${kind}:${this.current?.claim_id??'lane'}:${++this.requestSerial}`}
 async #heartbeat(){if(!this.session||this.mode==='stopped')return;const body=this.current?{mode:'working',ticket_id:this.current.ticket.id,...this.#authority()}:{mode:'waiting'};await this.#request('POST','/v1/workers/heartbeat',body);}
 #arm(){this.timer=setTimeout(()=>this.poll().catch(e=>this.#fail(e)),Math.max(0,this.nextPollAt-Date.now()));this.timer.unref?.();this.heartbeatTimer=setInterval(()=>this.#heartbeat().catch(e=>this.#fail(e)),this.heartbeatMs);this.heartbeatTimer.unref?.()}
 #disarm(){if(this.timer)clearTimeout(this.timer);if(this.heartbeatTimer)clearInterval(this.heartbeatTimer);this.timer=this.heartbeatTimer=null;this.abort?.abort();this.abort=null}
 async #deliver(claim){if(!claim?.ticket?.claim||typeof claim.claim_token!=='string')throw new Error('invalid_claim_response');this.current={ticket:claim.ticket,claim_id:claim.ticket.claim.claim_id,generation:claim.ticket.claim.generation,claim_token:claim.claim_token};this.mode='working';this.lastError=null;const history=(await this.#request('GET',`/v1/events?ticket=${encodeURIComponent(claim.ticket.id)}&after=0`)).value?.events??[];await this.#heartbeat();this.#notify();const prompt=['You are an unprivileged Pi pull worker. This canonical VIQ ticket contract and history are the sole task context.','Keep this claim until viq_submit, viq_release, or a blocking viq_question. A settled model turn is not completion. Never expose credentials or secrets.','','VIQ TICKET CONTRACT',JSON.stringify(claim.ticket,null,2),'','VIQ HISTORY',JSON.stringify(publicHistory(history),null,2)].join('\n');await this.deliver(prompt,claim.ticket);}
 async start({project,pollMs,once=false}={}){if(this.mode!=='stopped')throw new Error('worker_already_started');if(!this.credential)throw new Error('device_not_paired');await this.#identify();if(project!=null)this.project=clean(project,'project',20).toUpperCase();if(Number.isFinite(pollMs)&&pollMs>=250)this.pollMs=pollMs;await this.#open();this.mode='waiting';this.laneMode=once?'once':'persistent';this.rotationRequired=false;this.noWork=0;this.nextPollAt=Date.now();await this.#heartbeat();this.#notify();if(!once)this.#arm();await this.poll();if(once&&!this.current)await this.stop();return this.status()}
 async poll(){if(this.mode!=='waiting'||this.current||this.busy)return;this.busy=true;try{this.abort=new AbortController();const r=await this.#request('POST','/v1/tickets/claim-next',{worker_lease:true,...(this.project?{project:this.project}:{})},{signal:this.abort.signal});this.abort=null;if(r.status===204||!r.value){this.noWork++;this.nextPollAt=Date.now()+Math.min(60000,this.pollMs*2**Math.min(this.noWork,5));this.#notify();if(this.laneMode==='persistent'){if(this.timer)clearTimeout(this.timer);this.timer=setTimeout(()=>this.poll().catch(e=>this.#fail(e)),this.nextPollAt-Date.now());this.timer.unref?.()}return}this.noWork=0;await this.#deliver(r.value)}finally{this.busy=false}}
 async settled(){if(!this.current)return{active:false};const id=this.current.ticket.id,r=await this.#request('GET',`/v1/tickets/${encodeURIComponent(id)}`);const active=r.value?.ticket?.claim?.claim_id===this.current.claim_id&&r.value.ticket.claim.generation===this.current.generation;if(active)await this.#heartbeat();return{active,ticket:id};}
 async progress(message){const id=this.current.ticket.id;await this.#request('POST',`/v1/tickets/${encodeURIComponent(id)}/events`,{...this.#authority(),request_id:this.#requestId('progress'),message:clean(message,'message'),metadata:{worker:'pi-native'}});return{ticket:id}}
 async question(message,blocking=false){const id=this.current.ticket.id;await this.#request('POST',`/v1/tickets/${encodeURIComponent(id)}/questions`,{...this.#authority(),request_id:this.#requestId('question'),kind:'text',blocking,text:clean(message,'question'),target_type:'role',target_id:'reviewer'});if(blocking)await this.#terminal();return{ticket:id,blocking}}
 async block(message){const id=this.current.ticket.id;await this.#request('POST',`/v1/tickets/${encodeURIComponent(id)}/block`,{...this.#authority(),request_id:this.#requestId('block'),reason:clean(message,'reason')});return{ticket:id}}
 async submit(input={}){const id=this.current.ticket.id,bundle=input.version===1?normalizeReviewBundle(input):legacyReviewBundle({summary:clean(input.summary,'summary'),evidence:input.evidence});await this.#request('POST',`/v1/tickets/${encodeURIComponent(id)}/submit`,{...this.#authority(),reviewer:{type:'role',id:'reviewer'},message:`Outcome summary:\n${bundle.summary}`,review_bundle:bundle,request_id:this.#requestId('submit')});await this.#terminal();return{ticket:id}}
 async release(message){const id=this.current.ticket.id;await this.#request('POST',`/v1/tickets/${encodeURIComponent(id)}/release`,{...this.#authority(),request_id:this.#requestId('release'),release_message:`RELEASE: ${clean(message,'reason')}`,release_metadata:{worker:'pi-native'}});await this.#terminal();return{ticket:id}}
 async #terminal(){this.current=null;await this.#close();this.rotationRequired=true;this.mode='stopped';this.#disarm();this.#notify()}
 async stop(reason='operator stop'){this.#disarm();if(this.current)await this.release(reason);else if(this.session){try{await this.#request('POST','/v1/workers/heartbeat',{mode:'stopped'});await this.#close()}catch(e){this.#fail(e)}}this.mode='stopped';this.laneMode='stopped';this.project=null;this.#notify();return this.status()}
 shutdown(){return this.shutdownTask??=this.#shutdown()}
 async #shutdown(){try{return await this.stop('Pi session shutdown')}catch(error){this.mode='blocked';this.lastError=error instanceof Error?error.message:String(error);this.#notify();throw error}finally{if(this.mode==='stopped')this.shutdownTask=null}}
 async pair({code}){if(this.mode!=='stopped')throw new Error('stop_worker_before_pairing');const r=await this.#request('POST','/v1/devices/pair',{code:clean(code,'pairing_code',128)},{session:false,authenticated:false});this.setCredential(r.value?.credential);this.device=r.value?.device?.id;this.#notify();return r.value}
 async unpair(){if(this.mode!=='stopped')throw new Error('stop_worker_before_unpairing');this.credential=null;this.device=null;this.#notify()}
}
