const sanitizeEvents=events=>(events??[]).map(({cursor,type,actor,message,created_at})=>({cursor,type,actor,message,created_at}));
const cleanText=(value,name,max=8000)=>{if(typeof value!=='string'||!value.trim()||value.length>max)throw new Error(`invalid_${name}`);return value.trim()};
export class ViqWorkerRuntime{
 constructor({baseUrl='http://127.0.0.1:7373',pollMs=3000,deliver=async()=>{},onStatus=()=>{},fetchImpl=fetch,credential=null,syncVault=async()=>{throw new Error('vault_sync_not_configured')}}={}){this.baseUrl=baseUrl.replace(/\/$/,'');this.pollMs=pollMs;this.deliver=deliver;this.onStatus=onStatus;this.fetch=fetchImpl;this.syncVault=syncVault;this.credential=credential;this.mode='stopped';this.device=null;this.project=null;this.current=null;this.timer=null;this.busy=false;this.rotationRequired=false;this.lastError=null;this.session=null}
 status(){return{mode:this.mode,device:this.device,project:this.project,ticket:this.current?.ticket.id??null,rotation_required:this.rotationRequired,paired:Boolean(this.credential),last_error:this.lastError}}
 setCredential(value){if(typeof value!=='string'||value.length<32)throw new Error('invalid_device_credential');this.credential=value}
 #notify(){this.onStatus(this.status())}
 #error(error){this.lastError=error instanceof Error?error.message:String(error);this.#notify()}
 async #request(method,route,body,{authenticated=true}={}){if(authenticated&&!this.credential)throw new Error('device_not_paired');let response;try{response=await this.fetch(this.baseUrl+route,{method,headers:{'content-type':'application/json',...(authenticated?{authorization:`Bearer ${this.credential}`}:{}) ,...(this.session?.capability?{'x-viq-session-capability':this.session.capability}:{})},body:body===undefined?undefined:JSON.stringify(body)})}catch{throw new Error('viq_transport_error')}const text=await response.text();let value=null;try{value=text?JSON.parse(text):null}catch{throw new Error('viq_invalid_response')}if(!response.ok)throw new Error(value?.error?.code??`viq_http_${response.status}`);return{status:response.status,value}}
 async pair({code,id,name}){if(this.mode!=='stopped')throw new Error('stop_worker_before_pairing');const r=await this.#request('POST','/v1/devices/pair',{code:cleanText(code,'pairing_code',128),...(id==null?{}:{id:cleanText(id,'device_id',100)}),...(name==null?{}:{name:cleanText(name,'device_name',160)})},{authenticated:false});if(r.value?.device?.kind!=='worker'||typeof r.value?.credential!=='string')throw new Error('invalid_pairing_response');this.setCredential(r.value.credential);this.device=r.value.device.id;this.lastError=null;this.#notify();return{device:r.value.device,credential:r.value.credential}}
 #authority(){if(!this.current||!this.session)throw new Error('no_claimed_ticket');return{claim_id:this.current.claim_id,generation:this.current.generation,claim_token:this.current.claim_token}}
 async #openSession(){const r=await this.#request('POST','/v1/sessions',{});if(typeof r.value?.session_id!=='string'||typeof r.value?.session_capability!=='string')throw new Error('invalid_session_response');this.session={id:r.value.session_id,capability:r.value.session_capability}}
 async #closeSession(){if(!this.session)return;await this.#request('POST','/v1/sessions/close',{});this.session=null}
 async #orphanCheck(){const r=await this.#request('GET',`/v1/devices/${encodeURIComponent(this.device)}/claims`);const orphan=(r.value?.tickets??[])[0];if(orphan){this.mode='blocked';this.#notify();throw new Error(`orphan_claim_requires_operator:${orphan.id}`)}}
 async start({project,pollMs}={}){if(this.mode!=='stopped')throw new Error('worker_already_started');if(this.rotationRequired)throw new Error('rotation_required_start_fresh_session');if(!this.credential)throw new Error('device_not_paired');const me=await this.#request('GET','/v1/devices/me');if(me.value?.device?.kind!=='worker')throw new Error('paired_device_is_not_worker');this.device=me.value.device.id;if(typeof project!=='string'||!project.trim())throw new Error('project_required');this.project=project.trim().toUpperCase();if(Number.isFinite(pollMs)&&pollMs>=250)this.pollMs=pollMs;await this.#orphanCheck();await this.#openSession();this.mode='idle';this.lastError=null;this.#notify();this.timer=setInterval(()=>this.poll().catch(error=>this.#error(error)),this.pollMs);this.timer.unref?.();try{await this.poll()}catch(error){this.#error(error)}return this.status()}
 async poll(){if(this.mode!=='idle'||this.current||this.busy||this.rotationRequired)return;this.busy=true;try{await this.syncVault({phase:'readiness'});const r=await this.#request('POST','/v1/tickets/claim-next',{});if(r.status===204||!r.value){this.lastError=null;this.#notify();return}const claim=r.value;if(!claim.ticket?.claim||typeof claim.claim_token!=='string')throw new Error('invalid_claim_response');this.current={ticket:claim.ticket,claim_id:claim.ticket.claim.claim_id,generation:claim.ticket.claim.generation,claim_token:claim.claim_token};this.mode='claimed';this.lastError=null;this.#notify();let history;try{history=(await this.#request('GET',`/v1/events?ticket=${encodeURIComponent(claim.ticket.id)}&after=0`)).value?.events??[]}catch{await this.release('history fetch failed');throw new Error('history_fetch_failed')}const prompt=['You are an unprivileged Pi pull worker. This VIQ ticket contract and its VIQ history are the sole task context.','Keep this ticket claimed until you call viq_submit, viq_release, or viq_block. A model turn ending is not completion.','Use viq_progress for non-secret progress and viq_question for reviewer questions. Never include credentials or secrets in files, messages, or tool arguments.','','VIQ TICKET CONTRACT',JSON.stringify(claim.ticket,null,2),'','VIQ HISTORY',JSON.stringify(sanitizeEvents(history),null,2)].join('\n');await this.deliver(prompt)}finally{this.busy=false}}
 pause(){if(this.mode==='stopped')throw new Error('worker_not_started');if(this.mode==='idle')this.mode='paused';else if(this.mode==='claimed')this.mode='claimed_paused';this.#notify();return this.status()}
 resume(){if(this.rotationRequired)throw new Error('rotation_required_start_fresh_session');if(!['paused','claimed_paused'].includes(this.mode))throw new Error('worker_not_paused');this.mode=this.current?'claimed':'idle';this.#notify();if(!this.current)this.poll().catch(error=>this.#error(error));return this.status()}
 async progress(message){const a=this.#authority(),id=this.current.ticket.id;await this.#request('POST',`/v1/tickets/${encodeURIComponent(id)}/events`,{...a,message:cleanText(message,'message'),metadata:{worker:'pi-native'}});return{ok:true,ticket:id}}
 async question(message){const a=this.#authority(),id=this.current.ticket.id;await this.#request('POST',`/v1/tickets/${encodeURIComponent(id)}/questions`,{...a,kind:'text',text:cleanText(message,'question'),target_type:'role',target_id:'reviewer'});return{ok:true,ticket:id}}
 async block(message){const a=this.#authority(),id=this.current.ticket.id;await this.#request('POST',`/v1/tickets/${encodeURIComponent(id)}/block`,{...a,reason:cleanText(message,'reason')});this.mode='claimed_paused';this.#notify();return{ok:true,ticket:id}}
 async submit(message){const a=this.#authority(),id=this.current.ticket.id;let publication;try{publication=await this.syncVault({phase:'submission',ticket:id})}catch(error){this.#error(error);throw error}const evidence=`${cleanText(message,'evidence')}\n\nCanonical Vault commit: ${publication.commit}`;await this.#request('POST',`/v1/tickets/${encodeURIComponent(id)}/submit`,{...a,reviewer:{type:'role',id:'reviewer'},message:evidence});this.current=null;await this.#closeSession();this.rotationRequired=true;this.mode='paused';this.lastError=null;this.#notify();return{ok:true,ticket:id,rotation_required:true,commit:publication.commit}}
 async release(message){const a=this.#authority(),id=this.current.ticket.id;await this.#request('POST',`/v1/tickets/${encodeURIComponent(id)}/events`,{...a,message:`RELEASE: ${cleanText(message,'reason')}`,metadata:{worker:'pi-native',lane_state:'releasing'}});await this.#request('POST',`/v1/tickets/${encodeURIComponent(id)}/release`,a);this.current=null;await this.#closeSession();this.rotationRequired=true;this.mode='paused';this.lastError=null;this.#notify();return{ok:true,ticket:id,rotation_required:true}}
 async stop(reason='operator stop'){if(this.timer){clearInterval(this.timer);this.timer=null}if(this.current)await this.release(reason);else await this.#closeSession();this.mode='stopped';this.project=null;this.#notify();return this.status()}
 async shutdown(){if(this.timer){clearInterval(this.timer);this.timer=null}if(this.current){try{await this.release('Pi session shutdown')}catch{this.mode='blocked';this.#notify();return}}else try{await this.#closeSession()}catch{this.mode='blocked';this.#notify();return}this.mode='stopped';this.#notify()}
}
