#!/usr/bin/env node
import readline from 'node:readline';
import { HttpApplicationClient } from './http-client.js';
const string=(description)=>({type:'string',description}),integer={type:'integer',minimum:0},object=(properties,required=[])=>({type:'object',properties,required,additionalProperties:false}),out={type:'object',additionalProperties:true};
const id=string('Ticket ID');
export const tools=[
 ['device_me','Show this paired device.',object({})],
 ['device_list','List paired devices (coordinator only).',object({})],
 ['device_role_list','List device roles.',object({device_id:string('Device ID')},['device_id'])],
 ['role_list','List assignment roles.',object({})],
 ['project_list','List projects.',object({})],
 ['ticket_list','List visible tickets.',object({project:string('Project'),assignee_type:string('device, role, or none'),assignee_id:string('Assignee ID')},['project'])],
 ['ticket_get','Show visible ticket.',object({id},['id'])],
 ['ticket_next','Show next eligible assigned ticket without acquiring it.',object({project:string('Project')})],
 ['question_list','List visible ticket questions.',object({id,status:string('open or answered')},['id'])],
 ['event_list','List visible events.',object({project:string('Project'),ticket:id,after:integer})]
].map(([name,description,inputSchema])=>({name,description,inputSchema,outputSchema:out}));
const byName=new Map(tools.map(t=>[t.name,t]));
function invalid(schema,value){if(!value||typeof value!=='object'||Array.isArray(value))return true;if(schema.required.some(k=>!(k in value)))return true;if(Object.keys(value).some(k=>!(k in schema.properties)))return true;return Object.entries(value).some(([k,v])=>{const r=schema.properties[k];return r.type==='string'?(typeof v!=='string'||!v):r.type==='integer'?(!Number.isInteger(v)||v<(r.minimum??-Infinity)):false})}
function route(n,a){const t=encodeURIComponent(a.id??'');switch(n){case'device_me':return['GET','/v1/devices/me'];case'device_list':return['GET','/v1/devices'];case'device_role_list':return['GET',`/v1/devices/${encodeURIComponent(a.device_id)}/roles`];case'role_list':return['GET','/v1/roles'];case'project_list':return['GET','/v1/projects'];case'ticket_list':{const q=new URLSearchParams();if(a.assignee_type)q.set('assignee_type',a.assignee_type);if(a.assignee_id)q.set('assignee_id',a.assignee_id);return['GET',`/v1/projects/${encodeURIComponent(a.project)}/tickets?${q}`]}case'ticket_get':return['GET',`/v1/tickets/${t}`];case'ticket_next':{const q=new URLSearchParams();if(a.project)q.set('project',a.project);return['GET',`/v1/tickets/next?${q}`]}case'question_list':return['GET',`/v1/tickets/${t}/questions${a.status?`?status=${encodeURIComponent(a.status)}`:''}`];case'event_list':{const q=new URLSearchParams();if(a.project)q.set('project',a.project);if(a.ticket)q.set('ticket',a.ticket);if(a.after!=null)q.set('after',a.after);return['GET',`/v1/events?${q}`]}}}
const textResult=(structuredContent,isError=false)=>({content:[{type:'text',text:JSON.stringify(structuredContent)}],structuredContent,...(isError?{isError:true}:{})});
export function createMcpHandler({client=new HttpApplicationClient()}={}){return async m=>{if(m.jsonrpc!=='2.0'||!('id'in m))return null;const response={jsonrpc:'2.0',id:m.id};if(m.method==='initialize')return{...response,result:{protocolVersion:'2025-06-18',capabilities:{tools:{listChanged:false}},serverInfo:{name:'viqueue',version:'0.5.0-poc'}}};if(m.method==='ping')return{...response,result:{}};if(m.method==='tools/list')return{...response,result:{tools}};if(m.method==='tools/call'){const tool=byName.get(m.params?.name),args=m.params?.arguments??{};if(!tool)return{...response,error:{code:-32602,message:'Unknown tool'}};if(invalid(tool.inputSchema,args))return{...response,result:textResult({error:{code:'invalid_arguments',message:`arguments do not match ${tool.name} schema`,http_status:null}},true)};try{const[method,path]=route(tool.name,args);return{...response,result:textResult(await client.request(method,path))}}catch(error){return{...response,result:textResult({error:{code:error.code,message:error.message,http_status:error.http_status}},true)}}}return{...response,error:{code:-32601,message:'Method not found'}}}}
if(process.argv[1]&&import.meta.url===new URL(`file://${process.argv[1]}`).href){const handler=createMcpHandler(),lines=readline.createInterface({input:process.stdin,crlfDelay:Infinity});for await(const line of lines){if(!line.trim())continue;let response;try{response=await handler(JSON.parse(line))}catch{response={jsonrpc:'2.0',id:null,error:{code:-32700,message:'Parse error'}}}if(response)process.stdout.write(`${JSON.stringify(response)}\n`)}}
