#!/usr/bin/env node
import readline from 'node:readline';
import { HttpApplicationClient } from './http-client.js';
const string=(description)=>({type:'string',description}),integer={type:'integer',minimum:0},object=(properties,required=[])=>({type:'object',properties,required,additionalProperties:false}),out={type:'object',additionalProperties:true};
const id=string('Ticket ID'),target={target_type:string('device or role'),target_id:string('Target ID')};
const creds={id,claim_id:string('Claim ID'),claim_token:string('Claim token'),generation:{type:'integer',minimum:1}};
export const tools=[
 ['device_me','Show this paired device.',object({})],['device_list','List paired devices (coordinator only).',object({})],['device_revoke','Revoke a paired device (coordinator only).',object({device_id:string('Device ID')},['device_id'])],
 ['role_create','Create assignment role (coordinator only).',object({id:string('Role ID'),name:string('Name')},['id','name'])],['role_list','List assignment roles.',object({})],['device_role_list','List device roles.',object({device_id:string('Device ID')},['device_id'])],['role_grant','Grant assignment role (coordinator only).',object({device_id:string('Device ID'),role:string('Role ID')},['device_id','role'])],['role_revoke','Revoke assignment role (coordinator only).',object({device_id:string('Device ID'),role:string('Role ID')},['device_id','role'])],
 ['project_create','Create project (coordinator only).',object({key:string('Project key')},['key'])],['project_list','List projects.',object({})],
 ['ticket_create','Create/assign ticket (coordinator only).',object({project:string('Project'),title:string('Title'),body:string('Body'),assignee_type:string('device or role'),assignee_id:string('Assignee ID')},['project','title'])],['ticket_list','List visible tickets.',object({project:string('Project'),assignee_type:string('device, role, or none'),assignee_id:string('Assignee ID')},['project'])],['ticket_get','Show visible ticket.',object({id},['id'])],['ticket_next','Show next eligible assigned ticket.',object({project:string('Project')})],['ticket_claim_next','Atomically claim next eligible assigned ticket.',object({project:string('Project')})],['ticket_edit','Edit/assign ticket (coordinator only).',object({id,title:string('Title'),body:string('Body'),assignee_type:string('device, role, or none'),assignee_id:string('Assignee ID')},['id'])],['ticket_claim','Claim one exact eligible assigned ticket.',object({id},['id'])],
 ['claim_verify','Verify own claim.',object(creds,Object.keys(creds))],['claim_release','Release own claim.',object(creds,Object.keys(creds))],
 ['question_ask','Ask text question under own claim.',object({...creds,...target,text:string('Question')},[...Object.keys(creds),...Object.keys(target),'text'])],['question_list','List visible ticket questions.',object({id,status:string('open or answered')},['id'])],['question_answer','Answer question.',object({...creds,question_id:string('Question ID'),answer:string('Text answer'),decision:string('accept or request_changes'),note:string('Optional note')},['id','question_id'])],['event_post','Post progress under own claim.',object({...creds,message:string('Message'),metadata:{type:'object',additionalProperties:true}},[...Object.keys(creds),'message'])],['event_list','List visible events.',object({project:string('Project'),ticket:id,after:integer})],['ticket_submit','Submit own claim.',object({...creds,reviewer_type:string('device or role'),reviewer_id:string('Reviewer ID'),message:string('Message')},[...Object.keys(creds),'reviewer_type','reviewer_id'])],['ticket_accept','Accept submitted work (coordinator only).',object({id,message:string('Note')},['id'])],['ticket_reopen','Reopen ticket (coordinator only).',object({id,message:string('Message')},['id'])]
].map(([name,description,inputSchema])=>({name,description,inputSchema,outputSchema:out}));
const byName=new Map(tools.map(t=>[t.name,t]));
function invalid(schema,value){if(!value||typeof value!=='object'||Array.isArray(value))return true;if(schema.required.some(k=>!(k in value)))return true;if(Object.keys(value).some(k=>!(k in schema.properties)))return true;return Object.entries(value).some(([k,v])=>{const r=schema.properties[k];return r.type==='string'?(typeof v!=='string'||!v):r.type==='integer'?(!Number.isInteger(v)||v<(r.minimum??-Infinity)):r.type==='boolean'?typeof v!=='boolean':r.type==='object'?(typeof v!=='object'||Array.isArray(v)):false})}
function route(n,a){const t=encodeURIComponent(a.id??'');switch(n){case'device_me':return['GET','/v1/devices/me'];case'device_list':return['GET','/v1/devices'];case'device_revoke':return['POST',`/v1/devices/${encodeURIComponent(a.device_id)}/revoke`,{}];case'role_create':return['POST','/v1/roles',a];case'role_list':return['GET','/v1/roles'];case'device_role_list':return['GET',`/v1/devices/${encodeURIComponent(a.device_id)}/roles`];case'role_grant':return['PUT',`/v1/devices/${encodeURIComponent(a.device_id)}/roles/${encodeURIComponent(a.role)}`,{}];case'role_revoke':return['DELETE',`/v1/devices/${encodeURIComponent(a.device_id)}/roles/${encodeURIComponent(a.role)}`,{}];case'project_create':return['POST','/v1/projects',a];case'project_list':return['GET','/v1/projects'];case'ticket_create':{const{assignee_type,assignee_id,...rest}=a;return['POST','/v1/tickets',{...rest,...(assignee_type?{assignee:{type:assignee_type,id:assignee_id}}:{})}]}case'ticket_list':{const q=new URLSearchParams();if(a.assignee_type)q.set('assignee_type',a.assignee_type);if(a.assignee_id)q.set('assignee_id',a.assignee_id);return['GET',`/v1/projects/${encodeURIComponent(a.project)}/tickets?${q}`]}case'ticket_get':return['GET',`/v1/tickets/${t}`];case'ticket_next':{const q=new URLSearchParams();if(a.project)q.set('project',a.project);return['GET',`/v1/tickets/next?${q}`]}case'ticket_claim_next':return['POST','/v1/tickets/claim-next',{project:a.project}];case'ticket_edit':{const{assignee_type,assignee_id,...rest}=a;return['PATCH',`/v1/tickets/${t}`,{...rest,...(assignee_type?{assignee:assignee_type==='none'?null:{type:assignee_type,id:assignee_id}}:{})}]}case'ticket_claim':return['POST',`/v1/tickets/${t}/claim`,{}];case'claim_verify':return['POST',`/v1/tickets/${t}/verify`,a];case'claim_release':return['POST',`/v1/tickets/${t}/release`,a];case'question_ask':return['POST',`/v1/tickets/${t}/questions`,{...a,kind:'text'}];case'question_list':return['GET',`/v1/tickets/${t}/questions${a.status?`?status=${a.status}`:''}`];case'question_answer':return['POST',`/v1/tickets/${t}/questions/${encodeURIComponent(a.question_id)}/answer`,a];case'event_post':return['POST',`/v1/tickets/${t}/events`,a];case'event_list':{const q=new URLSearchParams();if(a.project)q.set('project',a.project);if(a.ticket)q.set('ticket',a.ticket);if(a.after!=null)q.set('after',a.after);return['GET',`/v1/events?${q}`]}case'ticket_submit':return['POST',`/v1/tickets/${t}/submit`,{...a,reviewer:{type:a.reviewer_type,id:a.reviewer_id}}];case'ticket_accept':return['POST',`/v1/tickets/${t}/accept`,a];case'ticket_reopen':return['POST',`/v1/tickets/${t}/reopen`,a]}}
const textResult=(structuredContent,isError=false)=>({content:[{type:'text',text:JSON.stringify(structuredContent)}],structuredContent,...(isError?{isError:true}:{})});
export function createMcpHandler({client=new HttpApplicationClient()}={}){return async m=>{if(m.jsonrpc!=='2.0'||!('id'in m))return null;const response={jsonrpc:'2.0',id:m.id};if(m.method==='initialize')return{...response,result:{protocolVersion:'2025-06-18',capabilities:{tools:{listChanged:false}},serverInfo:{name:'viqueue',version:'0.5.0-poc'}}};if(m.method==='ping')return{...response,result:{}};if(m.method==='tools/list')return{...response,result:{tools}};if(m.method==='tools/call'){const tool=byName.get(m.params?.name),args=m.params?.arguments??{};if(!tool)return{...response,error:{code:-32602,message:'Unknown tool'}};if(invalid(tool.inputSchema,args))return{...response,result:textResult({error:{code:'invalid_arguments',message:`arguments do not match ${tool.name} schema`,http_status:null}},true)};try{const[method,path,body]=route(tool.name,args);return{...response,result:textResult(await client.request(method,path,body))}}catch(error){return{...response,result:textResult({error:{code:error.code,message:error.message,http_status:error.http_status}},true)}}}return{...response,error:{code:-32601,message:'Method not found'}}}}
if(process.argv[1]&&import.meta.url===new URL(`file://${process.argv[1]}`).href){const handler=createMcpHandler(),lines=readline.createInterface({input:process.stdin,crlfDelay:Infinity});for await(const line of lines){if(!line.trim())continue;let response;try{response=await handler(JSON.parse(line))}catch{response={jsonrpc:'2.0',id:null,error:{code:-32700,message:'Parse error'}}}if(response)process.stdout.write(`${JSON.stringify(response)}\n`)}}
