#!/usr/bin/env node
import readline from 'node:readline'; import { HttpApplicationClient } from './http-client.js';
const string=(description)=>({type:'string',description}); const object=(properties,required=[])=>({type:'object',properties,required,additionalProperties:false});
const id=string('Ticket ID'); const credentials={id,claim_id:string('Claim ID'),actor:string('Claim actor'),claim_token:string('Opaque claim token'),generation:{type:'integer',minimum:1}}; const outputSchema={type:'object',additionalProperties:true};
export const tools=[
 ['project_create','Create a project.',object({key:string('Project key')},['key'])],['project_list','List projects.',object({})],
 ['ticket_create','Create an open ticket.',object({project:string('Project key'),title:string('Title'),body:string('Body'),assigned_to:string('Assignment')},['project','title'])],
 ['ticket_list','List project tickets.',object({project:string('Project key')},['project'])],['ticket_get','Show a ticket.',object({id},['id'])],
 ['ticket_next','Get the next ready ticket without claiming.',object({project:string('Optional project')})],
 ['ticket_edit','Edit ticket fields.',object({id,title:string('Title'),body:string('Body'),assigned_to:string('Assignment'),actor:string('Editor')},['id'])],
 ['ticket_claim','Claim an open ready ticket.',object({id,actor:string('Actor')},['id','actor'])],
 ['claim_verify','Verify current fenced claim authority.',object(credentials,Object.keys(credentials))],['claim_release','Explicitly release current claim.',object(credentials,Object.keys(credentials))],
 ['ticket_takeover','Explicitly take over a current claim.',object({id,actor:string('New actor')},['id','actor'])],
 ['event_post','Post a progress observation under current authority.',object({...credentials,message:string('Message')},[...Object.keys(credentials),'message'])],
 ['event_list','List events after a cursor.',object({project:string('Project'),ticket:id,after:{type:'integer',minimum:0}})],
 ['ticket_submit','Submit current work to review.',object({...credentials,message:string('Message')},Object.keys(credentials))],
 ['ticket_accept','Accept a review ticket.',object({id,actor:string('Actor'),message:string('Message')},['id','actor'])],
 ['ticket_reopen','Reopen review or done.',object({id,actor:string('Actor'),message:string('Message')},['id','actor'])]
].map(([name,description,inputSchema])=>({name,description,inputSchema,outputSchema}));
const byName=new Map(tools.map((tool)=>[tool.name,tool]));
function invalid(schema,value){if(!value||typeof value!=='object'||Array.isArray(value))return true;if(schema.required.some((k)=>!(k in value)))return true;if(Object.keys(value).some((k)=>!(k in schema.properties)))return true;return Object.entries(value).some(([k,v])=>{const r=schema.properties[k];return r.type==='string'?(typeof v!=='string'||!v):r.type==='integer'?(!Number.isInteger(v)||v<(r.minimum??-Infinity)):false;});}
function route(name,a){const ticket=encodeURIComponent(a.id??''); switch(name){case'project_create':return['POST','/v1/projects',a];case'project_list':return['GET','/v1/projects'];case'ticket_create':return['POST','/v1/tickets',a];case'ticket_list':return['GET',`/v1/projects/${encodeURIComponent(a.project)}/tickets`];case'ticket_get':return['GET',`/v1/tickets/${ticket}`];case'ticket_next':return['GET',`/v1/tickets/next${a.project?`?project=${encodeURIComponent(a.project)}`:''}`];case'ticket_edit':return['PATCH',`/v1/tickets/${ticket}`,a];case'ticket_claim':return['POST',`/v1/tickets/${ticket}/claim`,{actor:a.actor}];case'claim_verify':return['POST',`/v1/tickets/${ticket}/verify`,a];case'claim_release':return['POST',`/v1/tickets/${ticket}/release`,a];case'ticket_takeover':return['POST',`/v1/tickets/${ticket}/takeover`,a,{takeover:true}];case'event_post':return['POST',`/v1/tickets/${ticket}/events`,a];case'event_list':{const q=new URLSearchParams();if(a.project)q.set('project',a.project);if(a.ticket)q.set('ticket',a.ticket);if(a.after!=null)q.set('after',a.after);return['GET',`/v1/events?${q}`];}case'ticket_submit':return['POST',`/v1/tickets/${ticket}/submit`,a];case'ticket_accept':return['POST',`/v1/tickets/${ticket}/accept`,a,{takeover:true}];case'ticket_reopen':return['POST',`/v1/tickets/${ticket}/reopen`,a,{takeover:true}];}}
const textResult=(structuredContent,isError=false)=>({content:[{type:'text',text:JSON.stringify(structuredContent)}],structuredContent,...(isError?{isError:true}:{})});
export function createMcpHandler({client=new HttpApplicationClient({server:process.env.VIQ_SERVER,operatorToken:process.env.VIQ_OPERATOR_TOKEN})}={}){return async(message)=>{if(message.jsonrpc!=='2.0'||!('id'in message))return null;const response={jsonrpc:'2.0',id:message.id};if(message.method==='initialize')return{...response,result:{protocolVersion:'2025-06-18',capabilities:{tools:{listChanged:false}},serverInfo:{name:'viqueue',version:'0.3.0'}}};if(message.method==='ping')return{...response,result:{}};if(message.method==='tools/list')return{...response,result:{tools}};if(message.method==='tools/call'){const tool=byName.get(message.params?.name);if(!tool)return{...response,error:{code:-32602,message:'Unknown tool'}};const args=message.params?.arguments??{};if(invalid(tool.inputSchema,args))return{...response,result:textResult({error:{code:'invalid_arguments',message:`arguments do not match ${tool.name} schema`,http_status:null}},true)};try{const [method,path,body,options]=route(tool.name,args);return{...response,result:textResult(await client.request(method,path,body,options))};}catch(error){return{...response,result:textResult({error:{code:error.code,message:error.message,http_status:error.http_status}},true)};}}return{...response,error:{code:-32601,message:'Method not found'}};};}
if(process.argv[1]&&import.meta.url===new URL(`file://${process.argv[1]}`).href){const handler=createMcpHandler();const lines=readline.createInterface({input:process.stdin,crlfDelay:Infinity});for await(const line of lines){if(!line.trim())continue;let response;try{response=await handler(JSON.parse(line));}catch{response={jsonrpc:'2.0',id:null,error:{code:-32700,message:'Parse error'}};}if(response)process.stdout.write(`${JSON.stringify(response)}\n`);}}
